### ISSUE TITLE
Feature request: Ability to batch mode from multiple directories.

### ISSUE THREAD

**Issue by aevans0001** [sc0ty/subsync#107]
Basically I am most worried about my tv shows.  However my tv shows are in directory structure of Drive:\Shows\Adult\Show Title\Season #\Episode Number\Show.mkv

So when I want to batch process I have to copy everything out of the directories, sync it and then manually install it back into the directories.

This is a great program!

**Comment by sc0ty** [comment]
Sorry for the late reply, but you could add entire directory from menu File -> Add folder.
