### ISSUE TITLE
How to use headless?

### ISSUE THREAD

**Issue by csimpi** [sc0ty/subsync#110]
Hi, thank you for this great tool, sounds awesome but I couldn't find any documentation about how to use it from the command-line without the GUI?
Do I need all of the requirements when I want to use it without X? (I'm on Linux Debian)

A real-world example:
How can I auto-sync a video with English audio and a Hungarian subtitle?

Thx,
Peter

**Comment by sc0ty** [comment]
See here: https://github.com/sc0ty/subsync/wiki/Command-line-options
You don't need wxPython, everything else is required.

Example command for you:
`subsync --cli  sync --sub=path/to/subs.srt --sub-lang=hun --ref=path/to/movie.avi --ref-stream-by-type=audio --ref-lang=eng --out=/tmp/out.srt`
