### ISSUE TITLE
2 letter language code not working, always using 3

### ISSUE THREAD

**Issue by BelgianMonster** [sc0ty/subsync#111]
I have selected 2 letter language code but it always outputs 3 letters

**Comment by sc0ty** [comment]
Is this related to batch mode or normal synchronization? I can't reproduce it in normal mode.

**Comment by BelgianMonster** [comment]
Batch mode

Op zo 23 mei 2021 13:49 schreef Mike Szymaniak ***@***.***>:

**Comment by sc0ty** [comment]
This was not implemented in batch mode. Added appropriate option.
