### ISSUE TITLE
BUG: sub-lang / ref-lang parameters fail to recognize the "nld" ISO 639-3 code.

### ISSUE THREAD

**Issue by nurfed1** [sc0ty/subsync#112]
The [languages](https://github.com/sc0ty/subsync/blob/57f66724ed2692e4dad0b7bf557acb5970696de7/subsync/data/languages.py#L29) list defines "dut" as the ISO 639-3 code instead of "nld", I think "dut" is technically a "ISO 639-2" code. 
This creates issues with applications, such as bazarr, that do correctly select "nld" as the ISO 639-3 code.

Additionally, I did also notice that the "nld" code is defined in extraCodes. However extraCodes are not taken into account for --sub-lang / --ref-lang parameters. 

I won't create a pull request as I don't know the code base very well, but I believe a potential fix would be to change this behavior by modifying the following [line](https://github.com/sc0ty/subsync/blob/57f66724ed2692e4dad0b7bf557acb5970696de7/subsync/synchro/input.py#L65):
`
        self.lang = lang or self.lang
`
to
`        self.lang = languages.get(lang).code3 or self.lang
`

**Comment by menzo2003** [comment]
I've been having the same issue. Mostly subsync auto recognizes the language but it would better if this would work.
