### ISSUE TITLE
Feature request : Keep original TAG in output file

### ISSUE THREAD

**Issue by leger50** [sc0ty/subsync#116]
Hi,
First of all, thank you for this really helpfull tool ! I use it very often !

I was thinking, could it be possible to keep TAG of the original subtitles ?
I join two files to illustrate this : 
- New Girl (2011) S02E23.subsync.fre.srt (synchronized version via subsync)
- New Girl (2011) S02E23.origin.fre.srt (original subtitle from netflix)

If you look at subtitle item `7` : 
```
7
00:00:19,269 --> 00:00:20,312
{\an8}L'ARCHIDUC

# Became

7
00:00:19,142 --> 00:00:20,186
L'ARCHIDUC
```

Same example with subtitle item `40` : 
```
40
00:01:54,406 --> 00:01:56,908
{\an8}<i>C'était après le bal.</i>
<i>Cece et moi avions 18 ans</i>

# became

40
00:01:54,435 --> 00:01:56,941
<i>C'était après le bal.</i>
<i>Cece et moi avions 18 ans</i>
```
Those TAG can be pretty useful when some text credits are displayed, in this case `{\an}` will put the text at top of the screen instead of bottom, to be readable.
[subtitles_newgirl_s02e23_srtformat.zip](https://github.com/sc0ty/subsync/files/6417710/subtitles_newgirl_s02e23_srtformat.zip)

I don't know if it's possible.
Thank you for your time

**Comment by sc0ty** [comment]
I'm using external libraries to read/write subtitles so this is outside of my control.
But I can see that this TAG is preserved when you save your subtitles to ASS or SSA formats instead of SRT.
