### ISSUE TITLE
Bug: Subsync deletes original font tags in srt

### ISSUE THREAD

**Issue by michpas** [sc0ty/subsync#117]
Some original srt files have font colors (very handy in some situations; I won't go into)
An example is below, 
When this type of srt file is synced with a videofile, the output srt file omits what is between brackets <font color ....> and </font>
Interestingly the italic-tag **is** kept from the orginal to the output.

Request: Would it be possible to copy over all items between <> from the old srt to the newly synced str? 

Example below:

![tagsLost](https://user-images.githubusercontent.com/66222810/117585159-28ae3d00-b111-11eb-9933-b972c2f8c3c5.jpg)

**Comment by sc0ty** [comment]
I'm using external libraries to read/write subtitles so this is outside of my control.
Try to save to ASS/SSA format, they are better supported.
