### ISSUE TITLE
this is a great tool

### ISSUE THREAD

**Issue by wjcarpenter** [sc0ty/subsync#118]
I don't have an issue. I just wanted to leave a comment saying that I thought this was a great tool. I didn't have high hopes when I saw it in the snap store. I thought it was either be incredibly slow or would do a terrible job. I was wrong on both things. It takes about a minute or so on my fairly show computer to have enough points to enable the save box. And the matching is excellent. Thanks you so much for making this useful tool and having it actually do what you said it does. :-)

**Comment by sc0ty** [comment]
I'm glad it worked for you
