### ISSUE TITLE
save sync points to text file

### ISSUE THREAD

**Issue by kobygold** [sc0ty/subsync#123]
Hi,
Sometimes the subtitles we are trying to synchronize do not match the reference (movie) due to some scenes that were deleted (this happens quite a lot for older movies and TV shows that were changes to fit different audiences around the world). From the 'formula' on the GUI I guess the algorithm the tool is using is some linear regression (MMSE/Least Square Error), trying to fit the best linear line between sync points between input/reference. This algorithm will work well if the speed of the movie (for example: FPS) slightly changed, or if some offset was added at the beginning. But it will not work when some scenes were removed. Since the tool already finds sync points between the input/reference subtitles, it could be very useful if you could allow to save them to a text file (using some option on the GUI) and allow users to manually sync those special cases using this helpful data (or develop some sophisticated algorithm for synchronizing those cases in the future).

**Comment by sc0ty** [comment]
This option is available when you enable advanced debug options (in settings -> debug tab).
