### ISSUE TITLE
Failure to detect ISO-8859-1 encoding

### ISSUE THREAD

**Issue by 64kramsystem** [sc0ty/subsync#125]
Hello!

SubSync failed to detect the ISO-8859-1 encoding for several files. The files contains accented characters (e.g. `Voilà` in the 7F-FF range.

I suppose that SubSync misinterprets them for UTF-8 (`enca` misinterprets them as well).

Not sure if SubSync is supposed to detect the encoding in this case, so just throwing the issue out there :smile:.

**Comment by sc0ty** [comment]
Language detection is very simple. First it will try UTF-8 and if it fails, it fall backs to one defined for given language. For French it is Windows-1252.
You could always set encoding manually.
