### ISSUE TITLE
Following assets are missing on server: Chinese speech recognition model

### ISSUE THREAD

**Issue by TheCatLady** [sc0ty/subsync#13]
It appears that there might be a Mandarin Chinese model here: https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Mandarin/

**Comment by sc0ty** [comment]
I will look into this, thanks.
Should it be called Chinese or Mandarin? I can see that [ISO 639](https://www.loc.gov/standards/iso639-2/php/code_list.php) (which is used in media files) lists only Chinese.
Also we don't have any Mandarin dictionary yet.

**Comment by TheCatLady** [comment]
Mandarin is just one spoken dialect of Chinese, so I think it should be called Mandarin especially since the name of the model specifies it.

But when referring to written text, it's either Traditional Chinese (used in Taiwan & Hong Kong) or Simplified Chinese (used in mainland China).

**Comment by TheCatLady** [comment]
Chinese-English dictionary: https://www.mdbg.net/chinese/dictionary?page=cc-cedict

**Comment by sc0ty** [comment]
So the speech recognition model should be called Mandarin, and dicts should be Simplified Chinese / English and Traditional Chinese / English. Is the second one used with subtitles?

Currently models and dicts are marked only by ISO 3-letter code which corresponds with the country name. I will have to improve on this. I think I could add some extra field that will be used by next version of subsync, and current version will show them as Chinese.

**Comment by TheCatLady** [comment]
> So the speech recognition model should be called Mandarin, and dicts should be Simplified Chinese / English and Traditional Chinese / English. Is the second one used with subtitles?
Yes, exactly.  Alternatively, you could use zh-Hant (Traditional) and zh-Hans (Simplified) (specified by IETF and also RFC 5646).

**Comment by sc0ty** [comment]
Unfortunately current implementation is not working with Chinese. It expect to have words separated by spaces or punctuation. It needs different approach for non-alphabet based languages. I have some ideas, but hard to tell if it works out since I don't know this language.

**Comment by TheCatLady** [comment]
Ah, I see.  I think with Chinese, you'd want to try to match the longest series of characters to an entry in the dictionary (greedy match), since the meaning of a character can change depending on its context.  I'll keep brainstorming and let you know if I come up with any better ideas.

I can help test... I'm fluent in Mandarin. :)

**Comment by sc0ty** [comment]
Thanks for your help. I'll try simpler approach first. I was thinking about comparing substrings of 3 or 4 letters with dictionary that is structured similarly. Correlation logic could work with certain amount of invalid data (both false positives and false negatives), so maybe it will be good enough.

Is Chinese Simplified subset of the Traditional? Or have they some similarities? Maybe it would be enough to have single dictionary for these two.
Is Chinese read from left to right, top to bottom? I'm asking because I have some problems with Arabic synchronization due to its read direction.

**Comment by TheCatLady** [comment]
Simplified Chinese is not a subset of the Traditional.  Some characters may be the same, but they need to be separate dictionaries.  Simplified Chinese may also be more tricky, since words that are phonetically the same often use the same character whereas in Traditional Chinese, words with different meaning but the same pronunciation will have different characters.  This may result in translations from Simplified Chinese to English being a little less accurate.  Also, if text is to be translated *to* either Simplified or Traditional Chinese, you'll definitely need separate dictionaries or else the output will be a mix.

When written horizontally, Chinese is read left to right.

And just FYI -- I'm more comfortable reading Traditional Chinese than Simplified (as I'm Taiwanese and not Chinese).

**Comment by sc0ty** [comment]
I need this dictionary only to correlate words from different languages. In this (very specific) use case single dictionary could work (I think).
I have something working already, with dictionary generated from Wiktionary, but it has too little entries to be used reliably. I will try to add entries from dictionary you linked, but it is very descriptive which is far from optimal in my use case.

**Comment by sc0ty** [comment]
done
