### ISSUE TITLE
Missing Korean-English model 

### ISSUE THREAD

**Issue by Dnkhatri** [sc0ty/subsync#18]
Is it possible to get korean audio to english subtitle sync I keep getting this error
following assets are missing on server:

 - Korean speech recognition model

Traceback (most recent call last):
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/gui/errorwin.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/gui/mainwin.py", line 146, in start
    if assetsdlg.validateAssets(self, [task], askForLang=askForLang):
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/gui/components/assetsdlg.py", line 44, in validateAssets
    raise Error('\n'.join(msg))
subsync.error.Error: Following assets are missing on server:

 - Korean speech recognition model

**Comment by Dnkhatri** [comment]
I never found Korean speech recognition model. But I found this app for generating subs https://github.com/BingLingGroup/autosub
Would it be possible for subsync to call this app to get the subs for languages it does not have speech recognition model

**Comment by sc0ty** [comment]
You could generate subtitles manually and then use it as reference in subsync.

This app is using google speech-to-text API. I will try to use it too in subsync.

**Comment by Dnkhatri** [comment]
> You could generate subtitles manually and then use it as reference in subsync.
> 
> This app is using google speech-to-text API. I will try to use it too in subsync.

That's what I have been doing and got great results with the sync for korean. Haven't tried other languages yet.

**Comment by sc0ty** [comment]
Closing here since there is now #85 for asset requests.
