### ISSUE TITLE
Following assets are missing on server:   - dictionary English / Indonesian

### ISSUE THREAD

**Issue by rastaboy21** [sc0ty/subsync#21]
Thanks for this amazing tool! looking forward to using it on a regular basis. I tried used itl. but when I started doing Indonesia language I get this error.
as I saw from the issues some languages including the Indonesia dictionary is not available. can you please add it?

**Comment by sc0ty** [comment]
Added English/Indonesian and Hungarian/Indonesian dictionaries (from Wiktionary).
