### ISSUE TITLE
Missing asset: finnish speech recognition model

### ISSUE THREAD

**Issue by ikoutone** [sc0ty/subsync#25]
v0.11.0 seems to be missing Finnish speech recognition model. I'm not sure if there is one out there, or how you get them added in this software, but if there is then it would be awesome addition to this software.

**Comment by sc0ty** [comment]
There is no speech recognition model for Sphinx library and I couldn't find one on the internet.
See https://github.com/sc0ty/subsync/blob/master/doc/assets.md#speech-recognition-model

**Comment by sc0ty** [comment]
Closing here since there is now #85 for asset requests.
