### ISSUE TITLE
Problem with Crypto lib

### ISSUE THREAD

**Issue by Infray** [sc0ty/subsync#26]
I'm currently encountering following problem when trying to run subsync (in cli mode):

> 2019-11-09 13:11:39,231:  MainThread: WARNING:     subsync.assets.item: cannot load English speech recognition model: FileNotFoundError(2, 'No such file or directory')
> 
> 2019-11-09 13:11:39,232:  MainThread: WARNING:     subsync.assets.item: cannot load dictionary Dutch / English: FileNotFoundError(2, 'No such file or directory')
> 2019-11-09 13:11:40,724:    Download:   ERROR:  subsync.assets.updater: download failed, AttributeError("module 'Crypto' has no attribute 'Hash'")
> Traceback (most recent call last):
>   File "/app/subsync/subsync/assets/updater.py", line 71, in job
>     fp, hash = await self.download(fp)
>   File "/app/subsync/subsync/assets/updater.py", line 98, in download
>     hash = Crypto.Hash.SHA256.new()
> AttributeError: module 'Crypto' has no attribute 'Hash'
> [*] starting synchronization /shows/show/season/mediafile.srt
> [+] updating asset list
> 
> [+] downloading English speech recognition model        
> [!] FAILED
> [!] module 'Crypto' has no attribute 'Hash'

When I manually edit subsync/assets/updater.py to use 
> from Crypto.Hash import SHA256

it works fine.
Any idea why this is happening?

Kind Regards

**Comment by sc0ty** [comment]
They changed something in latest version of pycryptodome. Thanks for the fix.
Are you running it from snap out did you build it yourself?

**Comment by Infray** [comment]
No snap, I'm building my own container and pulling in the latest release (0.11).
