### ISSUE TITLE
pybind11 error

### ISSUE THREAD

**Issue by kram83** [sc0ty/subsync#27]
Dont know if its because i run subsync in a docker container but had my build error out last night with this message

```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNDEBUG=1 -I. -I/build/sphinxbase-5prealpha/ -I/build/sphinxbase-5prealpha/include -I/build/pocketsphinx-5prealpha/ -I/build/pocketsphinx-5prealpha/include -I/usr/include/python3.5m -c general/platform.cpp -o build/temp.linux-x86_64-3.5/general/platform.o -O3 -g -std=c++14 -fvisibility=hidden -fomit-frame-pointer -fexpensive-optimizations
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
general/platform.cpp:2:28: fatal error: pybind11/embed.h: No such file or directory
 #include <pybind11/embed.h>
                            ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```

had to re-add pybind11>=2.4.0 to the requirements.txt to fix it

**Comment by sc0ty** [comment]
pybind11 is specified in gizmo/setup.py in setup_requires so it should be installed during gizmo build.
I think it not belong to requirements.txt since it is not runtime requirement for subsync.

**Comment by kram83** [comment]
sorry for the late reply but i had the same results with 0.12.
When i tried it in a vm i noticed "cannot import pybind11" message when running setup.py

`test@ubuntu:~/subsync/gizmo$ python3 setup.py build
cannot import pybind11
running build
running build_ext
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c /tmp/tmpwi5bs0dj.cpp -o tmp/tmpwi5bs0dj.o -std=c++14
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c /tmp/tmplwuem3se.cpp -o tmp/tmplwuem3se.o -fvisibility=hidden
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c /tmp/tmp1uvwudv1.cpp -o tmp/tmp1uvwudv1.o -fomit-frame-pointer
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c /tmp/tmpocipd331.cpp -o tmp/tmpocipd331.o -fexpensive-optimizations
building 'gizmo' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/media
creating build/temp.linux-x86_64-3.6/text
creating build/temp.linux-x86_64-3.6/math
creating build/temp.linux-x86_64-3.6/general
creating build/temp.linux-x86_64-3.6/python
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNDEBUG=1 -I. -I/usr/local/include -I/usr/local/include/sphinxbase -I/usr/local/include/pocketsphinx -I/usr/local/include -I/usr/local/include/sphinxbase -I/usr/include/x86_64-linux-gnu -I/usr/include/python3.6m -c extractor.cpp -o build/temp.linux-x86_64-3.6/extractor.o -O3 -g -std=c++14 -fvisibility=hidden -fomit-frame-pointer -fexpensive-optimizations
extractor.cpp:5:10: fatal error: pybind11/pybind11.h: No such file or directory
 #include <pybind11/pybind11.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

any idea why it fails to import?

**Comment by sc0ty** [comment]
I have the same issue. You could always `pip install pybind11` before running setup.py.
I'm not sure how build dependencies should be defined in setuptools.

**Comment by sc0ty** [comment]
now it should work
