### ISSUE TITLE
Overwrite Subtitles & Save Settings

### ISSUE THREAD

**Issue by alekar231** [sc0ty/subsync#29]
Hey, 

New user here, thanks for this godsend of a software!
I'm not sure this is the right place to ask, but i have a couple things i'd like the dev know/answer about SubSync:

1. I only use batch processing, to be fair. Let's say i have english subtitles that are not synced. I use the software for x episodes and it creates **new files**. Is it not possible to overwrite the older ones (i.e. the not synced)? It always adds an "1" to the end of the file, since it doesn't overwrite. This is so annoying, i have to use a third party program to rename everything again.

2. Is it possible to save settings in batch processing?

Thank you so much

**Comment by sc0ty** [comment]
1. I'm planning to add option to overwrite files, just haven't time to do this yet.
2. What settings do you want to save? You could export list of files from "File" menu.

**Comment by alekar231** [comment]
1. That would be so good.
2. The output file names, for example, so it doesn't add the language code every time i make a new batch order.

**Comment by sc0ty** [comment]
2. I was certain that I did save this values. I must totally forgot about this. Will do.

**Comment by sc0ty** [comment]
Done and done

**Comment by alekar231** [comment]
Thanks
