### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by alekar231** [sc0ty/subsync#30]
"Error during reference read 
audio decoder failed: invalid data: Invalid data found when processing input 
averror: AVERROR INVALIDDATA code: -1094995529 
module: AudioDec.avcodec_send_packet 
source: media/audiodec.cpp:70 bool _cdecl struct AV
Packet time: 001458.197; 002224.844"

Does this happen due to an incompatible audio media?

**Comment by sc0ty** [comment]
Most likely your audio is corrupted. Have you tried to play it?
You could dump logs to be sure. In debug tab of settings set "logging level": all, select "log to file" and select where to save logs. Then run synchronization again.

**Comment by alekar231** [comment]
Audio is fine, i played it.
How can i share the log with you? It's 115mb

**Comment by sc0ty** [comment]
Stop the synchronization at first error. Also you could type "sphinx" into "Filter out logs from modules" in settings - we don't need logs from sphinx and there are lots of it.
You could attach files to comment, up to 25 MB. Compress it if needed.

**Comment by alekar231** [comment]
Wrote "sphinx" AND stopped at first error, still over 100mbs. Here's the link with the file: http://ge.tt/1PUXjnz2

**Comment by sc0ty** [comment]
It is a bug, probably related to https://trac.ffmpeg.org/ticket/1182
SubSync is spawning several audio decoding threads, every thread starts decoding from different place. This error is reported when it starts decoding audio packet not from the beginning. Only first packet fails to decode, so it should not have impact on synchronization.
As a workaround, you could try to set "Extractor jobs no" to 1 in settings, synchronization tab. It will run slower (in your case about 4 times slower), but it should finish without errors.

**Comment by alekar231** [comment]
Thanks. Any ETA on a fix?

**Comment by sc0ty** [comment]
Hard to say, I'm not sure how to fix it.
You could just ignore this error since it should not affect synchronization any in meaningful way.

**Comment by alekar231** [comment]
Thanks

**Comment by sc0ty** [comment]
Not sure how to correctly detect this situation, so ignoring this kind of error as workaround for now.
