### ISSUE TITLE
Danish dialogue support + "basic mode" feature request 

### ISSUE THREAD

**Issue by wellloaded** [sc0ty/subsync#31]
First of all thank you for this awesome software, it's genius!

I noticed that currently the spoken Danish is not supported so I was wondering if there's any plan to support this. Also I like a lot the option to synchronise subtitles with subtitles instead of video. Often movies come with strange subtitles format and OCR them is not easy/quick/simple so download a plain .srt version from Internet and using subsync is a wonderful function to have! Well done.

Beside this I have a minor feature request:

assuming the source subtitle file is simply offset compared to the dialog in the video file (great majority of the cases unless it's a re-edited/remasters/director-cut version), could SubSync have a "basic mode" where instead of trying to understand what the dialog says it would just try to match "voice" with "text"? This could be the default action if the audio language is left to "Unknown"... 

As a side note I initially posted this in the "wrong" subsync on github. It seems like there's another subsync https://github.com/smacke/subsync which funnily enough produces exactly what my feature request suggests, so perhaps this basic mode could be integrated here a well?

Regardless many thanks for the fantastic software!!

**Comment by sc0ty** [comment]
I'm using publicly available speech recognition models, [see](https://github.com/sc0ty/subsync/wiki/Assets#speech-recognition-model). I've never made any and I don't know how.

I'm aware of smackes subsync. My project works differently and adding language-agnostic synchronization would require a lot of work. I have some other ideas regarding both improving language-support and synchronization fragments of subtitles separately.

If the other app does what you need, just use it instead. I don't mind :)

**Comment by sc0ty** [comment]
Closing here since there is now #85 for asset requests.
