### ISSUE TITLE
Feature request: allow autosave

### ISSUE THREAD

**Issue by wellloaded** [sc0ty/subsync#32]
it would be really nice if the software would automatically save at the end of the re-sync period. Perhaps using the original filename as per source but appending "-resynced" to the auto saved file name.

Thanks!

**Comment by sc0ty** [comment]
That would require some additional consideration, probably some options in settings:
- what if file exists? Should be overwritten, saved with different name or not saved at all?
- when should it be saved? On initial synchronization or at the very end? What if user saved before? Overwrite it?

I don't think that would be useful enough to code it and I'd rather spend my time on improving synchronization.

Thanks for the input anyway.

**Comment by wellloaded** [comment]
Regardless on whether you will implement this or not (perhaps you can get contribution, you never know) just answering your points:

Point 1)
In my opinion you can either silently overwrite the 
subtitles-resynched.srt
if that's NOT the source file of the sync we're performing. Or to stay safe you can accept subtitles.srt as input and when the user presses Start you can prompt a writing confirmation if the auto-generated filename already exists.

Point 2)
I would just save this at the very end. Personally I'm happy to set the time to 180min and go to sleep but that's me.

**Comment by sc0ty** [comment]
Overwriting files silently is generally not a good idea and I'd like to do that only if the user explicitly agrees. Showing dialog at synchronization startup is not perfect either. What if new file would be created during synchronization?
And you could always use batch processing mode, it saves subtitles automatically.
About setting time to 180 min: personally I never had to set it more that default 30 min, but maybe your use case is different.
