### ISSUE TITLE
Provide arguments to subsync as a module

### ISSUE THREAD

**Issue by Infray** [sc0ty/subsync#34]
This is more of a question or feature request.

I would like to use subsync as a python module in my own script.
However after taking a look at your code I don't see an obvious way to provide arguments except by providing them via commandline.

How can I use subsync  as a module and provide arguments from my own script, so I don't have to use something like subprocess.

Thanks & Kind Regards
Infray

**Comment by sc0ty** [comment]
I'ts meant to be used as standalone app, not a python module so there is no straightforward way to use it from script. It would probably need some modification to pass arguments to [subsync()](https://github.com/sc0ty/subsync/blob/master/subsync/__main__.py#L14).

**Comment by Infray** [comment]
Modifying subsync() should serve my purpose (not tested it yet though) and should not have any impact on other use cases:
```
def subsync(argv=None):
    args = cmdargs.parseCmdArgs(argv)
```

I'm just not sure if this would be acceptable to you?
If it's OK then I'll create a PR.

**Comment by sc0ty** [comment]
Do it, i'll merge it.

**Comment by Benusnt** [comment]
Could this be used to add a post precessing script in Bazarr so it automatically checks the subs once downloaded ?

**Comment by sc0ty** [comment]
Ideally I would like to have something like this:
```
subsync(mode='sync', sub='sub.srt', sub_lang='pol', ref='movie.mkv', ref_stream=3, ...)
```
But I don't see how to (ab)use argparse that way.

@Benusnt I don't know about Bazarr, but if you could plug python script to it, then it should work.

**Comment by Infray** [comment]
Not sure I can help with that specific implementation unfortunately.

I usually write my modules with a method like you described. But I pass my arguments to that method after I've received them from argparse. You seem to be doing it the other way around.

But I never made anything as complicated as this project (with a gui and saving settings and stuff)

**Comment by sc0ty** [comment]
I think I will make separate functions like sync(sub, ref, ...) and batch(...), maybe also separate cli versions, but not right now.
I could accept yours version with argv if you want to have something working already.

**Comment by Infray** [comment]
I've created the pull request.
But your future solution will probably be much cleaner. ;)

**Comment by morpheus65535** [comment]
@sc0ty Hey, did you manage to implement those named arguments? I would like to be able to import subsync function into Bazarr (fully Python based subtitles downloader and manager) and use it to sync users subtitles. You can take a look at Bazarr [here](https://www.bazarr.media). Thanks!

**Comment by sc0ty** [comment]
Not yet, but I'm doing little refactor of the CLI mode and I'm planning to clean this up as part of this task. So hopefully soon.

**Comment by morpheus65535** [comment]
@sc0ty Thanks for the latest commit :-)

Any hint on how to use it?

**Comment by sc0ty** [comment]
Its not ready yet. When it will be ready, I'll let you know here.

**Comment by morpheus65535** [comment]
> Its not ready yet. When it will be ready, I'll let you know here.

Thanks! It's appreciated. :-)

**Comment by sc0ty** [comment]
It's finally done.
https://github.com/sc0ty/subsync/wiki/Python-API
https://subsync.online/doc/api/subsync/
