### ISSUE TITLE
Error during reference read

### ISSUE THREAD

**Issue by wellloaded** [sc0ty/subsync#35]
I've just got this error. English Sub and English audio:

> Error during reference read
> audio decoder failed: invalid data: Invalid data found when processing input
> averror: AVERROR_INVALIDDATA
> code: -1094995529
> module: AudioDec.avcodec_send_packet
> source: media/audiodec.cpp:70  bool __cdecl AudioDec::feed(const struct AVPacket *)
> time: 03:34:52.992

What does it mean?

**Comment by sc0ty** [comment]
Your reference is corrupted. It could be also bug #30.
Single error of this type shouldn't affect synchronization - only one audio packet is corrupted.
