### ISSUE TITLE
Provide .deb releases (or reduce package size)

### ISSUE THREAD

**Issue by Magissia** [sc0ty/subsync#37]
Currently, installing subsync snap result in 459Mb of software installed on a linux system, split in 4 snap files, including 262Mb for subsync_8.snap archive.

Providing a deb package would allow the software to use system's libraries to prevent wasting storage space :
We may already have sphinx installed, ffmpeg, pybind11 for other project installed system wide.

**Comment by sc0ty** [comment]
The problem with this approach would be that subsync needs quiet recent version of ffmpeg and pocketsphinx. In Ubuntu these packages are not available with needed version.
Also I have never build any deb and don't have time to research it right now, but pull requests are always welcome. Of course I would help with subsync build system specifics.

**Comment by Magissia** [comment]
The package you need are too old even in Ubuntu 20 ?

**Comment by sc0ty** [comment]
I can see that there is now ffmpeg 4.2 in Ubuntu 20 which would work. It would be great to support also 18.04 and some recent Debian version (at least).

**Comment by Migz93** [comment]
Would really appreciate if this was able to happen. I'm trying to get subsync installed within a bazarr container so i can use it to sync my subtitles as they download. Unfortunately the steps to build through python don't seem to work, and the container doesn't support snap so i can't use that either. If there was a deb package it'd make it much easier.
Understand you don't have experience in building a deb so not expecting anything anytime soon, just letting you know theres a want for a deb package.

**Comment by sc0ty** [comment]
Are debs distribution-dependent? If so, I would rather have something that runs on several systems, not only on single Ubuntu or Debian version.
Also it would be nice to have it in some ppa, allowing it to update automatically. Are there any community backed ppa servers that I could use? Or maybe it is easy

**Comment by sc0ty** [comment]
Closing since it duplicated #2
