### ISSUE TITLE
Headless Mode - Command Line Question

### ISSUE THREAD

**Issue by ulrick65** [sc0ty/subsync#38]
First off, this is one awesome piece of work...well done!  Works great.

I have been using the GUI in windows and all works great.  I am trying to automate it in Ubuntu and have it working, but I can't figure out how to get it to stop early and save the file rather than go through 100% scan.  In the the GUI, you can stop it once it reaches a probable completion and save the file.  Is there a command line arg that will do the same thing?  Like get 25 points and call it good and be done?

Thanks...great work here.

**Comment by sc0ty** [comment]
There is --effort switch for that. Setting this value to 0 will stop as soon as it reaches initial synchronization. You could experiment with values between 0 and 1.
Note that it will still count to 100% since that's progress indicator.

**Comment by ulrick65** [comment]
Thanks for the reply.  I did try setting it to --effort .25 and it didn't seem to speed it up or change anything.  I assume the higher that setting the more accurate it will be right?  I have never had an issue with the GUI...I always give it about 5 more points or so after it tells me I can save the file and I have never had an issue with subs being out of sync.

I will play around with it and experiment and see how it goes.  

Thanks again.  Great stuff here.

**Comment by sc0ty** [comment]
Higher value should take longer and produce more accurate output.

**Comment by ulrick65** [comment]
Ok, thanks.  I will play around with it when I get back to the project, not being able to write outside the folders (the snap issue) has me a bit stumped at the moment and I am working on another project right now.  Thanks for the feedback and support.  Great work!
