### ISSUE TITLE
Command line output shows incorrect filename created (kind of)

### ISSUE THREAD

**Issue by ulrick65** [sc0ty/subsync#39]
If the output file exists, it appends a .1 (or .2 or whatever version it is creating) but the output on the console says it created the file with the original filename.  Example:

If I tell it to --out sub.srt but that file already exists, it will create a file called sub.1.srt but the console output at the end will say that it created the file "sub.srt" when in fact it didn't.

Not a huge deal, but figured I would mention it.

Thanks again.  Loving this thing!

**Comment by sc0ty** [comment]
Thanks, will look into this.
GUI for batch processing is probably affected too.
