### ISSUE TITLE
If no write permission to output folder, it fails without error reason

### ISSUE THREAD

**Issue by ulrick65** [sc0ty/subsync#40]
If the output folder is not writeable by the user running it, it fails and says "gizmo.Error: can't open multimedia file: No such file or directory".  Nothing is output to the log file either.

Also, not a huge deal...but wanted to mention it that perhaps it should exit gracefully and give the reason why and output it into the log.

Thanks.

**Comment by sc0ty** [comment]
What system are you on? Are you using GUI or headless mode?
On Linux I have Permission denied (both with GUI and headless):
```
[Errno 13] Permission denied: '/bin/out.srt'

Traceback (most recent call last):
  File "/home/sc0ty/projects/subsync/subsync/gui/errorwin.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/home/sc0ty/projects/subsync/subsync/gui/syncwin.py", line 202, in onButtonSaveClick
    self.saveSynchronizedSubtitles(path, overwrite=True)
  File "/home/sc0ty/projects/subsync/subsync/gui/syncwin.py", line 211, in saveSynchronizedSubtitles
    self.sync.getSynchronizedSubtitles().save(path, encoding=enc, **kw)
  File "/home/sc0ty/projects/subsync/subsync/subtitle.py", line 52, in save
    super().save(path, encoding=encoding, format_=fmt, fps=fps)
  File "/home/sc0ty/projects/subsync/.env/lib/python3.8/site-packages/pysubs2/ssafile.py", line 197, in save
    with open(path, "w", encoding=encoding) as fp:
PermissionError: [Errno 13] Permission denied: '/bin/out.srt'
```

It's system error catched by generic exception handler, probably write errors should be handled separately with some custom error message.

**Comment by ulrick65** [comment]
I am on a headless Ubuntu 18.04, no GUI

**Comment by sc0ty** [comment]
I'm reproducing it now, when I run snap build. Handling it properly should be straightforward.

**Comment by sc0ty** [comment]
This exception is raised when input file can't be read, not because subtitles can't be written.
Are you having this issue when synchronization is starting?
Subtitles are written later, after synchronization is done. Output file is not opened before.
And gizmo module is not involved with saving file.

**Comment by ulrick65** [comment]
Here's what I get if I try to write to a folder outside of my home folder (which I do have write permission to, I can copy files there, delete them, etc. I have full access to the mounted folder)

15:21:20.019:  MainThread:   ERROR:             subsync.cli: task: SyncTask(sub=SubFile(path=/home/ulrick65/Primal (2019).en.srt:0/1, lang=eng, enc=UTF-8, type=subtitle/text), ref=RefFile(path=/home/ulrick65/Primal (2019).mkv:1/2, lang=eng, type=audio, fps=23.976023976023978), out=OutputFile(path=/mnt/DS1512-Write/Hold/Primal (2019).en.srt))
15:21:20.019:  MainThread:   ERROR:             subsync.cli: task failed, PermissionError(13, 'Permission denied')
Traceback (most recent call last):
  File "/snap/subsync/8/lib/python3.5/site-packages/subsync/cli.py", line 133, in runTasks
    self.synchronize(task)
  File "/snap/subsync/8/lib/python3.5/site-packages/subsync/cli.py", line 198, in synchronize
    overwrite=settings().overwrite)
  File "/snap/subsync/8/lib/python3.5/site-packages/subsync/subtitle.py", line 52, in save
    super().save(path, encoding=encoding, format_=fmt, fps=fps)
  File "/snap/subsync/8/lib/python3.5/site-packages/pysubs2/ssafile.py", line 197, in save
    with open(path, "w", encoding=encoding) as fp:
PermissionError: [Errno 13] Permission denied: '/mnt/DS1512-Write/Hold/Primal (2019).en.srt'

**Comment by ulrick65** [comment]
If I run the following command (it's a long one!) which is what I really want to do, I get the failure and nothing in the log file.

snap run subsync --cli --verbose 1 --logfile /home/ulrick65/log.txt sync --sub '/mnt/DS1512-Write/Hold/Primal (2019).en.srt' --ref '/mnt/DS1512-Write/Hold/Primal (2019).mkv' --out '/mnt/DS1512-Write/Hold/Primal (2019).en.srt'

Here's the output I get on the command line:

module: Demux.avformat_open_input
source: media/demux.cpp:51  Demux::Demux(const string&, std::function<bool()>)

**Comment by sc0ty** [comment]
It's caused by snap restrictions regarding filesystem access. You can access files in your home directory and resources mounted in media, but not in mnt.

**Comment by ulrick65** [comment]
I know why it is happening, I was just pointing out that it does not put anything in he log and basically gives the user the traceback in one case and in the second case, no real feedback as to what is going at all.

Not a big deal as I said...I just thought you might want to add some error trapping and gracefully exit with a message in the log as to why it is failing is all.

Thanks.
