### ISSUE TITLE
Question:  Why Snap?

### ISSUE THREAD

**Issue by ulrick65** [sc0ty/subsync#41]
I am not a programmer by any stretch, I can write some fairly good scripts in Python and Bash and I am pretty good with VBA (out of necessity)...I say this, because I am ignorant to the ways of programming something like you have here.

My question is why use Snap?  The reason I ask is because there are some limitations to it, one in particular that is kicking my butt and that is that the user that executes it must have a home directory in the $HOME folder...and mine does not.  I can run it as a test user, but the user I want to run it as has a home folder in /var/lib 

Is there anyway to run this as a straight Python program or something like that?  I see that someone asked about a .deb package as well...but I don't know kind of effort we are talking there.

I am coming up with a way to work around the issue, but I was just wondering for my own learning as to why and what the possibility was of something else.

Thanks again.

**Comment by sc0ty** [comment]
I admit that snap was not the best choice of package system for this app, see also #2.
You could build python module that can be used without package system https://github.com/sc0ty/subsync/blob/master/doc/install.md
You could also try to install SubSync in classic confinement mode https://snapcraft.io/docs/snap-confinement (with less restrictions, not recommended).

**Comment by ulrick65** [comment]
Thanks.  I appreciate the information and recommendations.  Again...great job with this thing, as far as I know there is nothing out there like it and I think it could be a very useful tool!

Happy New Year to you!
