### ISSUE TITLE
Timing offset

### ISSUE THREAD

**Issue by robertoglxda** [sc0ty/subsync#42]
Hi, and thanks a lot for this awesome project.

I've only a little issue, and I'm not sure if it is relevant only to the latest releases: I did not see this some time ago, so let me know if you want me to try on older versions.

Basically, after the syncronization is complete, I still see a timing offset of about -300ms (the subtitles are late of 300ms). The syncronization is otherwise correct, but all the subtitles have this offset.

As I'm not sure if it's only me of if it is an actual issue, I'd like to ask if it would possible to add a 'timing offset' options to work on this.

Thank you!

**Comment by sc0ty** [comment]
Synchronization algorithm is improved almost in every version so it could be regress introduced somewhere.
What languages are you using (subtitles and references)? I'm asking because some languages (Chinese, Japanese) are using different synchronization method that may not be tested thoroughly.
Also it would be very helpful if you could test against previous version(s).

Timing offset option would be nice to have but I'm not sure if it should be put in settings menu as global option, or in synchronization window, enabling per-file adjustments.

**Comment by robertoglxda** [comment]
Sorry for the delay. I'm using mostly english and italian, so I don't think it could be that.
I've done some tests, and I see now that both versions 0.4 and 0.13 give me this delay. I was probably missing it in the past, or using different video files. I'm not sure.
I'll update you if I can get some more info, I should be able to test the new setting you added in the meantime (I will build a new version myself from the sources).

Thank you!

**Comment by sc0ty** [comment]
How many synchronization points did you get?
Italian speech recognition model is pretty small, so if you are synchronizing with Italian audio, accuracy may be not perfect.

I got models from [here](https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/), I'm not making them myself.

**Comment by robertoglxda** [comment]
Sorry, I did not specified. I'm always using english as voice language, but english or italian for subtitles. I don't know if this is different for your models.
On the last test, I got 76 synchronization points. Everything is correct except for this delay, so I think that the recognition is actually working correctly except for the costant offset: apparently to me, every line is recognize correctly and moved correctly but with this offset.

**Comment by sc0ty** [comment]
It's released.
Also in this release I've tweaked correlation algorithm, cold you verify if you still have this problem?

**Comment by robertoglxda** [comment]
Thank you.
I've tried on some files and it seems to be working correctly with this release, however I'll need to play with it for a bit to be sure about this. I don't remember the files I used for the tests previously, sorry...

**Comment by pannal** [comment]
I've been using the latest version for a while now, with a lot of different series.

It syncs well, but for sub-to-audio sync, at least with English, it still shows the subtitles at least 150ms too late.

This might be personal preference, but subsync synced subtitles seem to start to display when the speech audio has a certain level already. It feels more natural to me to show the subtitles when the protagonist actually opens their mouth, which usually is between 100-250ms before the actual sound exists.

It would be great to have a flat offset option to account for this.


Great work.

**Comment by sc0ty** [comment]
It's already implemented
![image](https://user-images.githubusercontent.com/1812478/123784363-a869b400-d8d7-11eb-8d35-79a797b5f439.png)

**Comment by pannal** [comment]
Oh great, via command line as well?

**Comment by sc0ty** [comment]
--out-time-offset=OFFSET (in seconds)
See also https://github.com/sc0ty/subsync/wiki/Command-line-options#synchronization-options

**Comment by pannal** [comment]
@sc0ty I've just tried the option via the GUI in the latest release version (set to -0,190s); it didn't change anything in the output SRT, compared to the default (0,000), the offsets aren't modified at all.

Am I missing something essential?

**Comment by sc0ty** [comment]
Maybe try with some integer number to be sure?
Also look for line `adjusting timestamps by offset xxx` in the [logs](https://github.com/sc0ty/subsync/wiki/How-to-dump-logs)

**Comment by pannal** [comment]
Found the issue. When using subsync's default non-batch mode, the offset is completely ignored, no mentions of them in the log.
In batch mode the offset is used and applied:
`subsync.synchro.controller: adjusting timestamps by offset -0.100`

**Comment by pannal** [comment]
@sc0ty should I create a separate ticket for this issue?

**Comment by sc0ty** [comment]
It's fixed now, sorry for the delay
