### ISSUE TITLE
Missing setting

### ISSUE THREAD

**Issue by Doomhammer645** [sc0ty/subsync#47]
Hi I might be missing it completely but has the auto sorting of video and subtitle file when dragged and dropped in batch, been removed?
I know it exists in version 11, but can't see any setting nor am I asked to enable it, in newer versions.

**Comment by sc0ty** [comment]
Yeah, I've rewritten large part of batch window, it was a mess before. It would be hard to do this with current implementation. You could use add button or "Add files (auto sort)" from file menu.
I was thinking about making another drop target somewhere that adds with auto sort (e.g. next to the buttons), but didn't get to do this.

Another hack is: drop everything to references column and then drag to subtitles - if your videos have not subtitle tracks, they stay at references.

**Comment by Doomhammer645** [comment]
So is this something you'd think about Implementing eventually perhaps? (If possible).
Because it's a feature I rely heavily on, so that combined with the newer ones ability to delete and replace the previous subtitle file, would be incredible.

**Comment by sc0ty** [comment]
There is also auto sort button, I totally forgot.

**Comment by sc0ty** [comment]
It is released now.
