### ISSUE TITLE
Subsync won't launch from cmd.exe

### ISSUE THREAD

**Issue by zotoro** [sc0ty/subsync#48]
So the software GUI works great and I couldn't be happier, however I am having issues launching the program with command prompt. If I change the directory to C:\Program Files\subsync then type "subsync --help" nothing happens. However if I type just "help" without the subsync prefix, then the help options appear. Entering "subsync --help" in the root directory also does nothing. I cannot figure out how to launch the program from command prompt with arguments and any help would be appreciated.

Also, every once in awhile (maybe 1/50 subtitles) will throw the error that it is unable to be synced, Any ideas?

**Comment by sc0ty** [comment]
I can see that Windows version does not output to console. I'm using pyinstaller to create windows executables, I will look into its configuration.
You could use subsync-debug.exe as a workaround. It will output lots of logs, and may be slower, but it should work.

And why it can't synchronize everything: https://github.com/sc0ty/subsync/wiki/FAQ#why-it-failed-to-synchronize-my-subtitles

**Comment by zotoro** [comment]
So calling "subsync-debug --help" should work instead?

**Comment by sc0ty** [comment]
yep

**Comment by zotoro** [comment]
Works great! Thanks for the help. One final question, is it possible to have subsync auto overwrite files when run in headless mode? I didn't see anything about overwrite privileges in the wiki

**Comment by sc0ty** [comment]
There is `--overwrite` switch. I have to update wiki page.

**Comment by sc0ty** [comment]
I've added subsync-cmd.exe in version 0.14 to be used under Windows.

**Comment by zotoro** [comment]
Just wanted to let you know that calling 'subsync-cmd --cli....." from command prompt works perfectly on windows 10 pro now. Thanks for fixing this so quickly, you're awesome :)
