### ISSUE TITLE
(FEATURE REQUEST) add content from multiple folders

### ISSUE THREAD

**Issue by KonKar96** [sc0ty/subsync#49]
it would be great if we can select 10 movie folders for example and the program take the inside and sort them in a batch process 
this would help in big movie libraries from radarr that are in folders

**Comment by sc0ty** [comment]
You could select parent folder instead. Or drag & drop multiple folders and click "auto sort" button.
Unfortunately wxpython (GUI library) directory picker don't have any multi-selection mode that I know of.
