### ISSUE TITLE
Batch Processing - Can't hit start

### ISSUE THREAD

**Issue by ReiSixx9** [sc0ty/subsync#50]
I'm trying to batch process a bunch of subtitles for one video, but for some reason I can't hit the "start" button after adding all my files.

![](https://i.imgur.com/GqqKnRe.png)

**Comment by sc0ty** [comment]
You need one reference file for every subtitle file. So in your case you have to add S01E01.mkv multiple times.

**Comment by ReiSixx9** [comment]
> 
> 
> You need one reference file for every subtitle file. So in your case you have to add S01E01.mkv multiple times.

Thanks! What would you say the easiest way to add `S01E01.mkv` 27 times would be?

**Comment by sc0ty** [comment]
You could drag & drop it from file explorer, but you still have to do it 27 times.
I was thinking about adding some kind of copy-paste functionality, but there isn't any yet.
Alternatively you could export list to file (File -> Export list) and with text editor copy reference section in this file. Format of this list is pretty simple.

**Comment by ReiSixx9** [comment]
> 
> 
> You could drag & drop it from file explorer, but you still have to do it 27 times.
> I was thinking about adding some kind of copy-paste functionality, but there isn't any yet.
> Alternatively you could export list to file (File -> Export list) and with text editor copy reference section in this file. Format of this list is pretty simple.

Thanks a ton! Editing the exported list worked beautifully.

Can I download the Croation and/or Malay dictionaries or are these languages just not supported at all? 

![](https://i.imgur.com/I9OfGz5.png)
