### ISSUE TITLE
feature request: identify file type dropped on GUI

### ISSUE THREAD

**Issue by wellloaded** [sc0ty/subsync#51]
would it be possible for the GUI to place in the right field a dropped file?
so video in the video field and subtitle in the subtitles field, based on the extension?

At the moment I could mistakenly drop a video file over the subtitles field and all the way around.
Unless I'm missing something that's always unwanted.

Thanks

**Comment by sc0ty** [comment]
You could also synchronize subtitles with another subtitle file. Or you may want to synchronize subtitles that are inside video file.
Simple identification by format would prevent these scenarios.
