### ISSUE TITLE
Error - Synchronization Between Languages 

### ISSUE THREAD

**Issue by ReiSixx9** [sc0ty/subsync#53]
Can I download the Croatian and/or Malay dictionaries or are these languages just not supported at all?

![](https://i.imgur.com/I9OfGz5.png)

**Comment by sc0ty** [comment]
They are not supported.

**Comment by sc0ty** [comment]
And now they are.
I've updated import from Wiktionary and IATE (thats where I've got them from), and now we have some more dictionaries.

**Comment by ReiSixx9** [comment]
> 
> 
> And now they are.
> I've updated import from Wiktionary and IATE (thats where I've got them from), and now we have some more dictionaries.

Thanks again! :D
