### ISSUE TITLE
Feature request: Allow us to set reference type to always use audio

### ISSUE THREAD

**Issue by zotoro** [sc0ty/subsync#54]
I've noticed that despite all of my reference files being .mkv's, the synchronizer will sometimes select the audio track and other times the embedded subtitles to use as a reference type. I was wondering if it would be possible to set the synchronizer to always use the file's audio track, because whenever the synchronizer selects embedded subtitles my machine can take upwards of 3 hours to complete  the synchronization while using audio usually takes 5-30min depending on the file size.

Trying "--ref-type audio" is not a recognized command option.

Here are the current settings I'm using:
`subsync-cmd --cli --verbose 2 --jobs 0 --window-size 1800 --max-point-dist 0.6 --min-correlation 0.9999 --min-points-no 30 --min-word-len 4 --min-words-sim 0.6 sync --sub "{{subtitles}}" --ref "{{episode}}" --ref-lang eng --out "{{subtitles}}" --effort 0.75 --overwrite`

**Comment by sc0ty** [comment]
Currently there is no such option. You could always select track by its number using --ref-stream switch.
I was thinking about adding something like this before. I think i will add also switches to select track by language and maybe by name.

**Comment by sc0ty** [comment]
Added following switches:
--ref-stream-by-type=sub/audio
--ref-stream-by-lang and --sub-stream-by-lang

**Comment by zotoro** [comment]
Awesome, thank you! Is this live yet, or is it to be released with the next update? As of right now, using "--ref-stream-by-type audio" throws an unrecognized argument error and the application is showing that I'm up to date with the latest version.

**Comment by sc0ty** [comment]
Will be in next release.
