### ISSUE TITLE
Couldn't Sync Multiple Files

### ISSUE THREAD

**Issue by ReiSixx9** [sc0ty/subsync#56]
I recently synced about 30 subtitles to a video, but at the end of them all processing a few of them seemed to say the syncing failed. I decided to try and add these specific files to their own list and try and sync them again, but then I realized they're all the languages on "auto" so I was going to manually select all their languages, but none of the corresponding languages are in the drop down menu. I find it kinda odd that it didn't just tel me that these languages aren't supported or something before starting the process. Is there anything I can do about it to sync these subtitles?

The languages are;
- Vietnamese
- Thai
- Sinhalese
- Burmese
- Farsi/Persian
- Khmer/Cambodian

**Comment by sc0ty** [comment]
These languages are not supported - I don't have dictionaries for them.
And it should show popup saying something like "No language selected for <files> Are you sure?" unless you didn't disabled it either by checking "don't show this message again" during previous run, or from settings "Show popups: language not selected".

**Comment by ReiSixx9** [comment]
> 
> 
> These languages are not supported - I don't have dictionaries for them.
> And it should show popup saying something like "No language selected for Are you sure?" unless you didn't disabled it either by checking "don't show this message again" during previous run, or from settings "Show popups: language not selected".

Ah, that's unfortunate. There's no way to just sync via the time codes, like shift all the time codes within the subtitle(s) forwards or backwards 2 seconds?
Thanks anyways.

**Comment by sc0ty** [comment]
If you are asking about manual correcting the time codes, then no, subsync doesn't have that option. There are other apps that do just that.

**Comment by ReiSixx9** [comment]
> 
> 
> If you are asking about manual correcting the time codes, then no, subsync doesn't have that option. There are other apps that do just that.

Oh well. Thanks again! :)
