### ISSUE TITLE
"Synchronization with Japanese audio is currently not supported."

### ISSUE THREAD

**Issue by Hsys7272** [sc0ty/subsync#57]
I got this error today. It works really well on english just need japanese audio sync. 
Synchronization with Japanese audio is currently not supported.

missing assets:
 - Japanese speech recognition model

Traceback (most recent call last):
  File "subsync\gui\errorwin.py", line 75, in wrapper
  File "subsync\gui\mainwin.py", line 154, in start
  File "subsync\gui\components\assetsdlg.py", line 39, in validateAssets
  File "subsync\gui\components\assetsdlg.py", line 85, in raiseNotSupportedAssets
subsync.error.Error: Synchronization with Japanese audio is currently not supported.

missing assets:
 - Japanese speech recognition model

edit: I've tried this jp audio to jp subtitles
Let me know if I should close this one as others have already made requests similar to this.

**Comment by sc0ty** [comment]
I don't have Japanese audio recognition model, see https://github.com/sc0ty/subsync/wiki/Assets#speech-recognition-model

**Comment by sc0ty** [comment]
Closing here since there is now #85 for asset requests.
