### ISSUE TITLE
Syncing Keeps Failing

### ISSUE THREAD

**Issue by ReiSixx9** [sc0ty/subsync#59]
I've synced these files before using Subsync, but for some reason now none of them will successfully sync.

![](https://i.imgur.com/hY8p1dY.png)
[Here's the log.](https://github.com/sc0ty/subsync/files/4212284/Log.txt)

**Comment by sc0ty** [comment]
When you succeeded, you've synced them with previous version (0.13)?
In 0.14 I've changed slightly synchronization algorithm, now it could produces less synchronization points, but with better distribution.
From logs I can see that these subtitles are on the verge of being synchronized (except S01E03.ur.srt - did you forgot to select language for it?).
You could try to lower "synchronization points no" option in settings to e.g. 15.

**Comment by ReiSixx9** [comment]
> 
> 
> When you succeeded, you've synced them with previous version (0.13)?
> In 0.14 I've changed slightly synchronization algorithm, now it could produces less synchronization points, but with better distribution.
> From logs I can see that these subtitles are on the verge of being synchronized (except S01E03.ur.srt - did you forgot to select language for it?).
> You could try to lower "synchronization points no" option in settings to e.g. 15.

Hmm I'll give the synchronization points no thing a go, thanks. Also, I'm not sure if it like updated and I didn't notice or something, but when I succeeded it was a few days ago.

**Comment by ReiSixx9** [comment]
Ok, so that fixed all of the ar ones, but the ur one is still having issues and the ja one is still throwing this error.
![](https://i.imgur.com/EDWl7mV.png)

**Comment by sc0ty** [comment]
Could you attach this ja subtitles?

I've updated dictionaries recently, maybe thats what introduced regression? Here are the [old dicts](https://github.com/sc0ty/subsync/files/4225641/old-dicts.zip), you could try with them. Put them to `C:\ProgramData\subsync\assets\dict` and when subsync asks if you'd like to update them, don't.
