### ISSUE TITLE
sync files mkv with srt merge

### ISSUE THREAD

**Issue by rigas40** [sc0ty/subsync#61]
HI friend i have some files with srt merge with mkvtoolnix

is possible subsync  do sync inside mkv already have srt merge?

**Comment by sc0ty** [comment]
I'm not sure if I understand you correctly, but it is possible to synchronize subtitles merged with mkv. Just load it twice, as subtitles and as references, and select audio when opening as reference.
If you are asking if subsync can produce mkv file with synchronized subtitles, then no, it could only save results in subtitle format. I'm not planning to add such feature.

**Comment by rigas40** [comment]
yes idea it was sync srt is inside srt and save inside mkv new sync srt

**Comment by sc0ty** [comment]
I'ts not supported and I'm not planning to implement this. It would be complex and it wold take lots of my time, sorry.
