### ISSUE TITLE
Audio language detection

### ISSUE THREAD

**Issue by JpF4E** [sc0ty/subsync#62]
Hello, is audio language detection supported?
Is it mandatory to pass the `--ref-lang` parameter in the command line when our reference is an audio?

If detection isn't supported, is there a workaround?
I saw this comment in another issue: https://github.com/sc0ty/subsync/issues/18#issuecomment-531545217

**Comment by sc0ty** [comment]
There is no audio language detection (nor subtitle language for that matter). However languages could be encoded in some containers like avi, mkv, mp4. In that case subsync will use that information. It will also try to read language from file name if it ends with language code (before extension), e.g. `some.file.eng.srt`.
So specifying language is not mandatory in all cases.

One thing worth to mention: if you are synchronizing subtitles with references in another language, and subtitle language could not be detected using methods described above, proper dictionary will not be loaded and synchronization most likely fail. In that case you should set also `--sub-lang` manually.

**Comment by JpF4E** [comment]
Oh, right.
In my case, I always know the target subtitle language and my reference is always a video file, but I don't always know the audio language since I'm using Bazarr which gets the audio language from Sonarr/Radarr (which is not always correct).
Since there's no detection I guess I'll need to find a way to detect that audio language for the subtitles to sync correctly :)

**Comment by JpF4E** [comment]
There's this https://github.com/ssut/py-googletrans. It seems it can detect the language.
Do you think it would be feasible to integrate such thing with subsync?

**Comment by sc0ty** [comment]
If you'll select incorrect language, synchronization will most likely fail, so you probably may stop testing languages on first success.
I'm aware of py-googletrans and I was even thinking of using it as alternative speech-to-text engine. But this is an unofficial API to Google service, and Google is known for taking its (totally official) services down. Also I'm not sure if usage limits of API keys would be sufficient to synchronize anything. That's why I'm little afraid of investing my time for something like that.

**Comment by JpF4E** [comment]
> If you'll select incorrect language, synchronization will most likely fail, so you probably may stop testing languages on first success.

Well, the movie "Parasite" is Korean and there weren't assets available for Korean <-> Portuguese [also, this leads me to another question, where do you get these assets/dictionaries? Because I couldn't find any for Spanish <-> Portuguese as well] so I tried syncing it with English and the sync succeeded somehow... by the way, the lyrics were correctly synced which is even weirder given that subsync uses transcribed audio for syncing, if I'm right?.

My guess is that I probably need to know the audio language beforehand or go for the language testing to ensure that I have the best result.

**Comment by JpF4E** [comment]
> I'm aware of py-googletrans...

I edited that part out of my comment because, afterwards, I got the impression that lib was for text only. So it couldn't detect the language of an audio.
