### ISSUE TITLE
Dictionary missing

### ISSUE THREAD

**Issue by dnmaia** [sc0ty/subsync#67]
i'm using Bazarr  and the image "kocane/bazarr_subsync-sc0ty" which has the subsync built in, when runs in English subtitle it shows the message below

_BAZARR Post-processing result for file /TV shows/Spin.City.(1996).Season.1-6.S01-S06.(480p.DVD.x265.HEVC.10bit.AAC.2.0.Silence)/Season 01/Spin City (1996) - S01E01 - Pilot (480p DVD x265 Silence).mkv : [*] starting synchronization /TV shows/Spin.City.(1996).Season.1-6.S01-S06.(480p.DVD.x265.HEVC.10bit.AAC.2.0.Silence)/Season 01/Spin City (1996) - S01E01 - Pilot (480p DVD x265 Silence).en.srt [+] synchronization 0%: 0 points [+] synchronization 91%: 90 points [+] synchronization 100%: 135 points [+] synchronization 100%: 160 points [+] saving to /TV shows/Spin.City.(1996).Season.1-6.S01-S06.(480p.DVD.x265.HEVC.10bit.AAC.2.0.Silence)/Season 01/Spin City (1996) - S01E01 - Pilot (480p DVD x265 Silence).en.srt [+] done_

which looks ok, but when the subtitles is in portuguese, it shows this:

_BAZARR Post-processing result for file /TV shows/Spin.City.(1996).Season.1-6.S01-S06.(480p.DVD.x265.HEVC.10bit.AAC.2.0.Silence)/Season 01/Spin City (1996) - S01E01 - Pilot (480p DVD x265 Silence).mkv : [*] starting synchronization /TV shows/Spin.City.(1996).Season.1-6.S01-S06.(480p.DVD.x265.HEVC.10bit.AAC.2.0.Silence)/Season 01/Spin City (1996) - S01E01 - Pilot (480p DVD x265 Silence).pt-BR.srt [+] updating asset list [!] there is no assets needed to perform synchronization [-] asset dictionary English / pob is missing_

So, it is still syncronizing or i need to add this dictionary to work well, and if so, how can i do it?

**Comment by sc0ty** [comment]
Duplicated #66
