### ISSUE TITLE
Error on syncronizing

### ISSUE THREAD

**Issue by dnmaia** [sc0ty/subsync#68]
Hi, i'm with on case now that, every time i try to synchronize that subtitle in English it shows the result below. some times reaches 100% but still say, couldn't syncronize.:

_

> BAZARR Post-processing result for file /movies/FullHD/The X Files (1998)/The.X.files.1998.1080p.BDRip.x265.AC3-Webhiker.mkv : [*] starting synchronization /movies/FullHD/The X Files (1998)/The.X.files.1998.1080p.BDRip.x265.AC3-Webhiker.en.srt [+] synchronization 0%: 0 points [+] synchronization 18%: 13 points [+] synchronization 24%: 16 points [+] synchronization 30%: 20 points [+] synchronization 28%: 20 points [+] synchronization 29%: 20 points [+] synchronization 31%: 20 points [+] synchronization 36%: 20 points [+] synchronization 39%: 20 points [+] synchronization 48%: 20 points [+] synchronization 75%: 20 points [+] synchronization 91%: 20 points [-] couldn't synchronize!

_

**Comment by sc0ty** [comment]
Probably is one of the cases that subsync can't sync https://github.com/sc0ty/subsync/wiki/FAQ#why-it-failed-to-synchronize-my-subtitles
And it always reaches 100% it's just glitch in printing status.

**Comment by dnmaia** [comment]
yeah, you are Right. something wrong with the file.
