### ISSUE TITLE
[IDEAS] Multisync and Sync between subs

### ISSUE THREAD

**Issue by forart** [sc0ty/subsync#69]
Hi there, very interesting and useful tool.

Here's my suggestions:

1. Multisynch: sync multiple language subtitles (it would be great to select more than one from the original subs files) with the destination one.

2. Since not all speech models are available, why not syncing with destination subs (if available).

Hope that inspires.

**Comment by sc0ty** [comment]
1. I was thinking about it myself. Would require some work. Probably eventually will do.
2. That's already implemented.
