### ISSUE TITLE
Bug synchronize subtitles

### ISSUE THREAD

**Issue by leger50** [sc0ty/subsync#7]
Hello ! First of all, it's a great idea !
I wanted to try your software but the subtitles are not synchronized correctly. It seems that there is a shift of about 6 seconds.
I have the subtitles file if you want ("desynchronized.srt") and a file where the times would be correct (shifted manually) : "synchronized.srt".

I tried to understand the problem and noticed that the subtitles had broken sentences like :

> A lit-t-le breck-y could be good for me.
No, no, no, st-ay focused. Speed.

Is this the reason ? 
Thanks for your time (I'am also sorry for my bad English)

[subtitles.zip](https://github.com/sc0ty/subsync/files/3091189/subtitles.zip)

**Comment by sc0ty** [comment]
That's probably the case. How many synchronization points did you get? And what are you synchronizing with?
Also if you could dump reference words I could investigate it further. To do it:
- open settings window, go to "Debug" tab and select "enable advanced debug options"
- after synchronization you will see extra button next to save and close. Click it and then "Dump reference words".
Thanks

**Comment by leger50** [comment]
Thank you for the answer.
I did it again, I got 327 synchronization points.
You will find in attachment the file of subtitle generated by subsync ("desynchronized.srt"), the dump of references words ("referencesWords.eng.srt") and a file csv which contains points of synchronization used ("synchronizedPoints.csv").

I synchronized the animated movie "Cars", with an english audio track (AAC3, 48000Hz).
I hope this can help you.

[subtitlesDump.zip](https://github.com/sc0ty/subsync/files/3095524/subtitlesDump.zip)

**Comment by sc0ty** [comment]
Could you also provide input subtitles?
Are they in English or other language?

**Comment by leger50** [comment]
For sure.
I zip the subtitles generated by the software and subtitles that I shifted manually. These are English subtitles.
If you need other things, ask me.
[subtitles.zip](https://github.com/sc0ty/subsync/files/3099077/subtitles.zip)

**Comment by sc0ty** [comment]
It's the result of synchronization, but could you upload also the source subtitles? The ones before you synchronized them?

**Comment by leger50** [comment]
Hello, sorry for the delay, here are the original subtitles of the movie.
[sourcesSubtitles.zip](https://github.com/sc0ty/subsync/files/3101332/sourcesSubtitles.zip)

**Comment by sc0ty** [comment]
That's strange, I cannot reproduce this. I've got similar results as yours synchronized.srt.
Are you using latest version of subsync? (0.9)
Could you dump logs from synchronization? To do that go to settings -> debug tab, select "login level: all", check "log to file" and save logs somewhere.

**Comment by leger50** [comment]
Hello, I tried again and I don't understand, I didn't change anything, but the subtitles are synchronized correctly (version is 0.9).
I tried several times to redo the "bug" by modifying the subtitles source file but it was ok.
I apologize for the lost time, the problem probably had to come from my pc and not the software.
I thank you for this tool which is really very practical! 
My apologize again
