### ISSUE TITLE
[IDEA] Styled sub sync/copy

### ISSUE THREAD

**Issue by forart** [sc0ty/subsync#70]
I just discovered that - since the sync is great - the result file don't keep the source sub style.

It would also be great to let users decide wich (source or destination) style should be copied.

Hope that inspires !

**Comment by sc0ty** [comment]
Styling is partially preserved, depends of the file format. For best results use ASS/SSA formats.
What do you mean by deciding which style should be copied? It's always from input subtitles.

**Comment by forart** [comment]
Well, none of the synchronizations I made (50+) preserved sub style.

If the software can disclose if both subs (source and destination) are styled, then when you start sync it could ask if you wanna keep style or what style (source or destination) you wanna copy/apply.

Hope it's clearly expalined.

**Comment by sc0ty** [comment]
I've just checked and it worked for me for ASS subtitles. Styles were preserved when saved for ASS and SSA formats.
What file formats are you using? Or maybe you are running some old version of subsync? Style support was added in version 0.11.

And what would be the use case for using styles from another file? In most situations styles wouldn't even have proper names. I don't wan't to make some general use subtitle editor, just a tool to fix timestamps, that leave everything else unchanged (including styles).

Anyway, thanks for your input.

**Comment by forart** [comment]
Both source and destination subs was (embedded in mkv) ASS.

Latest SubSync version, of course.

**Comment by sc0ty** [comment]
It should work. I will check that later.
By destination you mean reference?
And in what format are you saving synchronized subtitles? Because default SRT has no support for styles, only inline styling like bold or italic.

**Comment by forart** [comment]
The software don't ask anything about it, and in settings I can only choose the encoding output.

I honestly don't know if I've set something wrong (i used default settings), btw I believe that clearer dialog boxes can help users more.

**Comment by sc0ty** [comment]
It's when you're saving subtitles, you could change file format, in the same dialog where you are entering file name and location.

**Comment by forart** [comment]
Ok here's a visual demonstration:
Source sub (to sync): https://i31.servimg.com/u/f31/16/32/04/85/source10.jpg
Dest sub (to be synched with): https://i31.servimg.com/u/f31/16/32/04/85/dest10.jpg
Result: https://i31.servimg.com/u/f31/16/32/04/85/result10.jpg

I also tried both SUB and SSA with the same result: source style gone.

Hope that helps.

**Comment by sc0ty** [comment]
I can see that source and result are both italic, but have different fonts. Could you upload these subtitles? You could use e.g. [MKVExtractGUI](https://sourceforge.net/projects/mkvextractgui-2/) to extract subtitles from MKV.

I don't see how styles from reference (your dest sub) could be used in output. Currently input subtitles have time codes fixed and its content is not changed (except format conversion).
To apply styles from reference subtitles you need to decide somehow which style should be set to which line (and reference subtitles could have lines split differently). And there are also inline styles (styling part of the line, e.g. single word) which would be even more complex.

**Comment by forart** [comment]
...unfortunally MKVExtractGUI don't work in my system...

BTW here's the extracted "mks" by MKVtoolnix: https://clicknupload.co/yw2jd0tqa7me

**Comment by sc0ty** [comment]
Are you on Linux? I remember that on some Linux platforms extension is not changed when you select the output format in the save dialog. You have to change it manually.
Also have you looked inside output subtitles to check if its not saved as srt? Can you also post it somewhere? Preferably as an attachment to reply.

**Comment by forart** [comment]
Here's the result files, both in ASS and SSA: https://clicknupload.co/yc5tg09m92de

No, I'm on Windows.

**Comment by sc0ty** [comment]
Sorry for this long delay.
You're right that the embedded fonts are the problem.
I don't know if ASS/SSA formats supports embedded fonts, but library I'm using (pysubs2) is not, so subsync will not support it either, sorry.
