### ISSUE TITLE
command windows

### ISSUE THREAD

**Issue by rigas40** [sc0ty/subsync#72]
I am trying run headless cli command 

i am getting error

MainThread: WARNING: subsync.translations: translation language setup failed, FileNotFoundError(2, 'No translation file found for domain'

**Comment by sc0ty** [comment]
It looks like it fails to load GUI translations. It should fallback to English and work despite this error.
Could you get logs with parameter `--loglevel=DEBUG`?

**Comment by rigas40** [comment]
i am using this way 
subsync-cmd.exe --cli sync --sub=asd.srt --sub-stream=1 --sub-lang=por --ref=movie.mkv --ref-stream=2 --ref-lang=eng --out=asd.srt --overwrite

**Comment by sc0ty** [comment]
What do you want to achieve? After the --cli switch you need to specify what to do, see https://github.com/sc0ty/subsync/wiki/Command-line-options

**Comment by rigas40** [comment]
yes but for run in headless in windows i need use subsync-cmd.exe --cli  or subsync.exe --cli ?

**Comment by sc0ty** [comment]
You should use subsync-cmd.exe. subsync.exe will not print to standard output.
