### ISSUE TITLE
Greek language extension

### ISSUE THREAD

**Issue by arpal-jpg** [sc0ty/subsync#75]
Greek subtitles are given the extension "gre" that is not recognized in Plex (In fact they appear as unknown.  Also, bazarr saves greek srt files with the "el" extension, which is the one that eventually Plex recognizes.  Is it possible to automatically save as "el" without changing custom names in batch options?

**Comment by sc0ty** [comment]
That's because subsync is using 3-letter codes as in ISO 639. Will add option to append also 2-letter codes.

**Comment by kalligator** [comment]
Kindly note that ISO 639-2/B abbreviations which are used in the app, are not based on the native names of languages in many cases (inc. Greek, German, French and any more) but rather on the English translation of the name of the language. More info [here](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).
It is therefore more appropriate to use 639-2/T and of course the 639-1 (two letters) option is more than welcome as it's most popular.

**Comment by sc0ty** [comment]
I'm using 2/B because they are used inside media files. Maybe I should add also 2/T for language detection also.

**Comment by kalligator** [comment]
Did not know that, indeed it seems so. 
Funnily enough I found [this page](https://support.plex.tv/articles/200220717-local-media-assets-tv-shows/#toc-3) on Plex that says that it supports '2/B and '1 yet OP reports it fails with '2/B.
