### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by jobrien2001** [sc0ty/subsync#77]
Hello,

I am monitoring CPU usage and initially it starts off at 100% on all available cores then after 28% or so goes down to using only 1 core at 100%.

Is this intended?

**Comment by sc0ty** [comment]
There are two types of tasks that are running during synchronization: extractor and correlator.
Extractor task is reading file and producing words annotated with timestamps for correlator. It splits subtitles or performs speech recognition, depending on stream type. There are multiple instances of extractors running simultaneously, one reading input subtitles, and one or more reading reference audio/subtitles.
Correlator is working on data produced by extractors to synchronize subtitles. There is only single instance of correlator that runs single thread.

So when all extractors are finished reading files, only correlator process is left working on single core. Typically this is the case when you are synchronizing subtitles with another subtitle file. Extractors are done early, producing lots of data to process by correlator.
When you're synchronizing with audio, speech recognition slows down extractors and correlator is starved most of the time, waiting for data to process.

Good news is, you could stop synchronization early. And when you synchronizing with subtitles, usually its a good idea. Synchronization with subtitles produces much more data that is typically needed by correlator. You could just save subtitles before it ends (after initial synchronization, save button is unlocked). In headless mode you could use `--effort=0.2` or even 0.1 to achieve similar goal. Default value is 0.5 and its tuned for synchronization with audio.

Why is correlator single threaded? Rewriting it would require lots of work and would most likely introduce lots of bugs. Instead I'm planning to introduce better defaults that would stop synchronization with subtitles earlier.

**Comment by jobrien2001** [comment]
Hi, thank you for the response.

I used type audio on the command line, not sub.  A sync takes about 10 minutes on a movie.  Is this usually time required?  I should leave effort at 0.5 since i am using audio?

**Comment by sc0ty** [comment]
Synchronization time depends on many variables, but I would say that everything between 5 - 20 minutes is ok. [Dump logs](https://github.com/sc0ty/subsync/wiki/How-to-dump-logs) and post it here, maybe I'll find out why it runs so long after extractors are done.

You could try to decrease effort, but it could result with subtitles not synchronized correctly, so better check if they align with video.

**Comment by jobrien2001** [comment]
Hi, here are some debug logs:

[subsync1.txt](https://github.com/sc0ty/subsync/files/4522589/subsync1.txt)

**Comment by sc0ty** [comment]
I can see that this synchronization took about 2 minutes, not 10. Is that correct? And all 24 extractor threads are running almost to the end.
Maybe your hard drive is the bottleneck, and now Test.mkv is cached in ram? 24 extractors are reading it at 24 different offsets, it adds up to pretty high disk bandwidth.

**Comment by jobrien2001** [comment]
Yes, perhaps it was the file and language.

I tried another that took ~10 min

[subsync1.txt](https://github.com/sc0ty/subsync/files/4525724/subsync1.txt)

**Comment by sc0ty** [comment]
You have lots of synchronization points which means that correlator has lots of high quality data to work on. It is usually a good thing, but processing it takes some time. If this is typical situation for you (I would expect that it is typical for Spanish subtitles synchronized with English audio) then you could safely lower effort to 0.1. With that value it would stop after about 3 minutes.
I'm planning to improve synchronization algorithm to fix this exact issue - it should stop when it detects that more work has little to no effect.

**Comment by wellloaded** [comment]
On this point, I have a 24 cores device and when SubSync runs it completely hogs the operative system (program freeze, folder browsing turns grey e.g. busy), etc.
I really don't mind SubSync working in background and taking all the resources it needs, but I think it should run with way lower priority compared to what the defaults are. I have tried lowering the process priority myself and it did somehow improve but not as much as expected. I would suggest introducing a maximum number of cores or in general introducing options to lower the impact on the system (even if this results in a longer time to synchronise).

Thanks

**Comment by sc0ty** [comment]
Subsync is actually lowering extractor threads priority. With 24 threads you may also hit disk bandwidth limit.
And there is already such option: `--jobs <no>` from command line or "extractor jobs no" in settings menu.

**Comment by wellloaded** [comment]
I would say if the 24 cores can all go to 100% and stay constantly they are indeed the bottleneck before any other components. e.g.

![image](https://user-images.githubusercontent.com/46318040/82159541-c799b380-9886-11ea-8639-710b7f4bb4f2.png)

Regardless I have now tweaked the jobs no as suggested. Thanks!

**Comment by sc0ty** [comment]
Yeah you right.
Maybe I should limit threads no for machines with a lots of cores by default. How many `--jobs` works for you?
I've never run subsync on anything that has more than 6 cores hyper-threaded (12 threads).

**Comment by wellloaded** [comment]
I have set it to 16 and it behaved better. I did not run many tests though...
