### ISSUE TITLE
Enchantment : Add translate option.

### ISSUE THREAD

**Issue by asyba** [sc0ty/subsync#78]
An enchantment can be add option to translate the subtitle to another language.
Sometimes the only resource I found is in English.
Currently I'm using this simple web [https://translatesubtitles.com/translate.php](https://translatesubtitles.com/translate.php) that use Google Translate I think.
Is not 100% accurate but is close.

**Comment by sc0ty** [comment]
See https://github.com/sc0ty/subsync/wiki/FAQ#why-dont-you-just-generate-subtitles-from-audio-like-youtube
