### ISSUE TITLE
Prevent Windows from going into sleep mode

### ISSUE THREAD

**Issue by KevinDenis** [sc0ty/subsync#79]
Setup batch-processing job, Windows went into sleep-mode while processing subtitles.
Subsync should prevent Windows from going into sleep mode.

Side effect from going into sleep mode; ETA did not work anymore as Time Elapsed kept on counting when Windows was in sleep mode.

**Comment by sc0ty** [comment]
Good idea, it looks like wxPython can do that in portable manner - https://wxpython.org/Phoenix/docs/html/wx.PowerResourceBlocker.html#wx-powerresourceblocker.
I will also add settings option to disable this.

**Comment by sc0ty** [comment]
Done, but only in GUI mode. Needs wxPython 4.1.0 or newer and currently works only on Windows and OS X.
Details: https://wxpython.org/Phoenix/docs/html/wx.PowerResource.html
