### ISSUE TITLE
error on Ubuntu 18.04

### ISSUE THREAD

**Issue by huuub** [sc0ty/subsync#8]
Can't get it to work. I tried using it with snapd
error : 
subsync --sub="t.srt" --sub-stream=1 --sub-lang=nl --ref='./t.mkv' --ref-stream=1 --ref-lang=tm --out="out.srt" --auto=done --logfile log

```Traceback (most recent call last):
  File "/snap/subsync/4/bin/subsync", line 11, in <module>
    load_entry_point('subsync==0.9.0', 'gui_scripts', 'subsync')()
  File "/snap/subsync/4/lib/python3.5/site-packages/subsync/__main__.py", line 21, in subsync
    subs, refs, args = parseCmdArgs(sys.argv)
  File "/snap/subsync/4/lib/python3.5/site-packages/subsync/__main__.py", line 138, in parseCmdArgs
    subs = Stream(path=args.sub, types=('subtitle/text',))
  File "/snap/subsync/4/lib/python3.5/site-packages/subsync/stream.py", line 18, in __init__
    self.open(path)
  File "/snap/subsync/4/lib/python3.5/site-packages/subsync/stream.py", line 27, in open
    ss = gizmo.Demux(path).getStreamsInfo()
gizmo.Error: can't open multimedia file: Permission denied
code: -13
file: t.srt
module: Demux.avformat_open_input
source: media/demux.cpp:37  Demux::Demux(const string&)
```

**Comment by sc0ty** [comment]
Snaps has limited access to filesystem. Subsync could access only user home directory and mounted media. If your files are somewhere else, it may not be visible to subsync.
Please check if you could navigate to your file via GUI to be sure.
You could override this behaviour if you trust me enough using [classic confinement](https://docs.snapcraft.io/snap-confinement/6233).

**Comment by huuub** [comment]
hmmm that did not help :
sudo snap install subsync --classic
Warning: flag --classic ignored for strictly confined snap subsync

subsync 0.9 from Michał Szymaniak (sc0typl) installed

**Comment by huuub** [comment]
I installed with dev-mode... That worked but now I get: 
subsync \
> --sub='/media/data/complete/tvsonarr/Game of T/Season 8/t.srt' \
> --sub-stream=1 \
> --sub-lang=nl \
> --ref='/media/data/complete/tvsonarr/Game of T/Season 8/t.mkv' \
> --ref-stream=1 \
> --ref-lang=en \
> --out="/media/data/complete/tvsonarr/Game of T/Season 8/out.srt" \
> --auto=done

```
Traceback (most recent call last):
  File "/snap/subsync/4/bin/subsync", line 11, in <module>
    load_entry_point('subsync==0.9.0', 'gui_scripts', 'subsync')()
  File "/snap/subsync/4/lib/python3.5/site-packages/subsync/__main__.py", line 21, in subsync
    subs, refs, args = parseCmdArgs(sys.argv)
  File "/snap/subsync/4/lib/python3.5/site-packages/subsync/__main__.py", line 146, in parseCmdArgs
    refs.select(args.ref_stream - 1)
  File "/snap/subsync/4/lib/python3.5/site-packages/subsync/stream.py", line 63, in select
    stream = self.streams[no]
KeyError: 0
```

**Comment by sc0ty** [comment]
Are you trying to run it without graphical desktop environment? It won't work that way, even when run from terminal it still tries to show GUI.

**Comment by huuub** [comment]
Hmmm there is even x11 interface on docker. But a pity. Was really looking forward to integrate it with bazarr

**Comment by sc0ty** [comment]
I am working on command line version already, I think it will be included in the next release. Not sure what bazarr is (nor sonarr or radarr which google is pointing me to), but I understand you need version of subsync to be called from terminal or some kind of script?

And I'm not sure why you can't use classic confinement, my knowledge of snaps is rather limited.

About your command line parameters - languages are selected with three letter codes. So you should use --ref-lang=eng and --sub-lang=dut (I think).
I will describe command line arguments extensively when I'll have command line version ready.

**Comment by huuub** [comment]
Sounds great! I also don't know anything about snaps... I would prefer docker :)

**Comment by linderlake** [comment]
I had this issue and after struggling a bit I ended up here on google. So for future reference I will add my solution below:

1. re-install the subsync snap package with --classic flag (this step might not be needed but I did this)
2. issue "sudo snap connect subsync:removable-media", this will give subsync permissions to your removable storage (ie the folders in /media/).

That's it.

**Comment by sc0ty** [comment]
removable-media is already listed in plugin section in snap.yaml, it should have access to /media without extra steps (and user home dir).

**Comment by Erbros** [comment]
> 2. issue "sudo snap connect subsync:removable-media", this will give subsync permissions to your removable storage (ie the folders in /media/).
Thank you! This fixed my issue as well. I didn't need step 1.
