### ISSUE TITLE
Output detected language without sub processing

### ISSUE THREAD

**Issue by jobrien2001** [sc0ty/subsync#80]
Many files are released with incorrectly tagged or undetermined (und) language.

Since language is already being recognized by subsync, it could it be possible to remux and tag the file with the detected language manually or batch with FFMPEG or MKVtoolnix.

It would be nice to have a something like this:

`subsync --cli detectlanguage --ref test.mkv`

Then output the track id (mkvmerge of ffmpeg), detected language, metadata language, and an accuracy rating (1-100) like so:
`3 eng und 80`

An application of this would be to loop all video files to subsync and remuxing with the detected language where the  rating exceeds a certain threshold.

**Comment by sc0ty** [comment]
But subsync is not detecting languages, not based of the track data.
If the tag is missing or `und` it looks for filename - it checks if there is 2- or 3-letters language code before file extension. That's all what's done to determine language.

I was thinking about subtitle language detection by words lookup in dictionaries, but haven't actually done that.
