### ISSUE TITLE
What subtitles formats are accepted as sync reference?

### ISSUE THREAD

**Issue by wellloaded** [sc0ty/subsync#81]
I have few .mkv files with built in subs and I'm trying to synchronise external subtitles with the internal one. (external being .srt internal it varies), usually same language but not necessarily.
Result: I often see only audio tracks in the video reference file.

So my question is:
- is there a list of reference subtitle format supported?

Thanks

**Comment by sc0ty** [comment]
Subsync works only with text-based subtitles. You are probably have bitmap-based subtitles which are not supported.

**Comment by wellloaded** [comment]
Right... but could the timing only from the bitmap subtitles be used?
Just an idea...

**Comment by sc0ty** [comment]
Current algorithm won't work with only time codes.
Maybe some day I will try to integrate some OCR solution.
