### ISSUE TITLE
Log Rotate on a daily basis ?

### ISSUE THREAD

**Issue by TRaSH-** [sc0ty/subsync#83]
Using the command line option and I wonder if it would be possible to add the option to rotate the logs on a daily basis ?
Or does is rotate at a certain size ?

**Comment by sc0ty** [comment]
Normally this is done by additional software, like [logrotate](https://linux.die.net/man/8/logrotate).
And logs in subsync was meant mainly for debug purposes, but of course your use case may be different.

**Comment by TRaSH-** [comment]
The reason why i want sort of logs is because i use it together with Bazarr in dockers,
and i would like to keep a eye on what's actually being synced.

**Comment by sc0ty** [comment]
subsync will not do that, use logrotate
