### ISSUE TITLE
Can subsync correct subtitles that include more voice lines than are in the corresponding video file?

### ISSUE THREAD

**Issue by Ocman76** [sc0ty/subsync#84]
Hello,

First off I'd like to thank you for developing Subsync, its awesome.

My question stems from noticing some issues with synced subtitles to episodes where the original subtitles file was for a longer version of the episode (with recap before episode) than the video file. When I sync subtitles which include subtitles for a 2 minute recap before the episode begins, they don't sync correctly.  The video file starts off with the subtitles very far off, up to 15 seconds depending on the episode.  However interestingly enough, as the episode continues the subtitles get closer and closer to being correct, in that the offset decreases from say 15 seconds to 14, then 13 and so on until eventually the subtitles are playing at the correct times.  Sometimes this happens quite quickly, over the span of only a few minutes, and sometimes it takes half the episode.

Subsync never produces any errors when syncing subtitles and video files which do not have the same amount of voice lines.  I have tried increasing the effort to 0.75 as well as the max adjustment to 45 minutes but the issue persists.  Is it not possible for subsync to sync these kind of subtitle and video pairings?

Thank you!

**Comment by sc0ty** [comment]
I've just tested something similar and I think I know whats going on.
Your recap subtitles instead of being discarded are getting timecodes 0:00:00,000 (or something similar, depending on file format). Probably your video player has minimal duration time for showing subtitles and shows this recap lines, delaying whats next. When you finally got some interval between subtitles, it will catch up with current lines.
Could you verify if your synchronized subtitles have some zero-time lines at the beginning? And if you remove them, will they show correctly?
Thanks.

**Comment by Ocman76** [comment]
Hey Sc0ty, thanks for the quick reply!

I tried looking at the srt files of a few of the instances where I've been having the issue I previously described and some of them do have lines of 0:00:00,000 at the beginning to indicate the lines are not needed for the video.  However not all of them do, and the files that do have 0:00:00,000 lines at the beginning are actually episodes where the subtitle file and video file are synced correctly!  Removing the 0:00:00,000 lines from the .srt does not change the playback (they are still synced correctly).  It appears the issue only occurs in some episodes, and in those ones there are no lines with 0:00:00,000 timestamps present, the subtitles in the .srt file are simply timestamped at the wrong time in the beginning of the video and then slowly get better as the video progresses as I described before.  Would it help if I went through and found more files where I am having this issue so I could try to find some similarities that could pass off to you?  They must have something in common that is causing the subtitles to sync incorrectly...

**Comment by sc0ty** [comment]
It should work with extra lines at the beginning, but you may have subtitles that can't be synchronized with subsync algorithm, e.g. subtitles for tv rip and blu ray video that has some minor differences like different opening. See [FAQ](https://github.com/sc0ty/subsync/wiki/FAQ#why-it-failed-to-synchronize-my-subtitles).

Could you run command `subsync --dump-words refRaw:c:\dump\here\ref.srt --loglevel=DEBUG --logfile=c:\dump\here\log.txt` and run some failing synchronization and then share with me generated ref.srt, log.txt and your subtitles? This command will dump transcripted audio as subtitles. That way I could check it myself without your big video file. Of course replace `c:\dump\here` with some path that you have write access to.
Thanks.

**Comment by Ocman76** [comment]
Hey Sc0ty,

I've been trying to run the command as well as the failing synchronization via command prompt but am having trouble getting everything to work.  I have no coding knowledge so fitting together the commands from the wiki is not exactly a cake walk, would you be able to provide me a little help on what additional commands need to be entered after the first one you gave me?  I am able to get that first command to work but have not been able to get the synchronization to work via commands after it.

**Comment by sc0ty** [comment]
Just run this single command (with correct paths) and run synchronization from GUI as you did before.

**Comment by Ocman76** [comment]
I ran the command as well as the synchronization via GUI but the resulting .srt file doesn't appear to contain a dump of the transcripted audio as subtitles.  Here are all the relevant files:
[log.txt](https://github.com/sc0ty/subsync/files/4666300/log.txt)

[The Expanse - S03E09 - Intransigence.eng (SYCHRONIZED).txt](https://github.com/sc0ty/subsync/files/4666301/The.Expanse.-.S03E09.-.Intransigence.eng.SYCHRONIZED.txt)

[The Expanse - S03E09 - Intransigence.en (Original).txt](https://github.com/sc0ty/subsync/files/4666303/The.Expanse.-.S03E09.-.Intransigence.en.Original.txt)

**Comment by sc0ty** [comment]
You didn't get the logs from synchronization, I can see only app starting and then nothing.
You running subsync.exe, not subsync-cmd.exe right?
Are you seeing main window when you run this command?
Any error shows up?
Could you post exact command that you are running?

**Comment by Ocman76** [comment]
I was using subsync-cmd.exe, that was my problem haha.

Here are the resulting files:
[log.txt](https://github.com/sc0ty/subsync/files/4679574/log.txt)
[dump.txt](https://github.com/sc0ty/subsync/files/4679575/dump.txt)
[The Expanse - S03E09 - Intransigence.eng (SYCHRONIZED).txt](https://github.com/sc0ty/subsync/files/4679576/The.Expanse.-.S03E09.-.Intransigence.eng.SYCHRONIZED.txt)

I see in the dump file that Subsync is able to detect words starting at around 12 seconds into the video, however it doesn't start any subtitles until over a minute in, not sure exactly why.

**Comment by sc0ty** [comment]
It's like I was thinking before, subsync algorithm can't handle this synchronization. That's because subsync is analyzing subtitles globally and is changing delay and pitch for all of them at once. Your subtitles need different delay at the beginning than the rest of it.
If you cut them at about 8 minute and synchronize both parts separately, you will get proper synchronization for both parts with different delays. Probably this subtitles was created for episode that is cut differently at this point around 8 minute. That is often the case between TV version and BluRay/DVD.

I'm planning to add support for something like that, but probably not so soon. I don't know how to do it right now, only have some ideas that need experimenting.

Great show by the way.

**Comment by Ocman76** [comment]
Ah I see, that makes sense.  Thanks for all the help, I use Subsync for lots of TV shows and it works great!  Cheers!
