### ISSUE TITLE
 FileNotFoundError(2, 'No translation file found for domain')

### ISSUE THREAD

**Issue by Tupilak** [sc0ty/subsync#86]
I am running Subsync from a bat file and I did notest this error pop up.

MainThread:  WARNING:       subsync.translations: translation language setup failed, FileNotFoundError(2, 'No translation file found for domain')

I am using version 0.15.0.
The video I use is in English, and the SRT file in danish. The GUI will not open the video file, and I just get a error telling me 
"Traceback (most recent call last):
  File "subsync\gui\errorwin.py", line 75, in wrapper
  File "subsync\gui\openwin.py", line 67, in openStream"
so I switch the commandline insted. And I do work, just wabt the error to go away.

**Comment by sc0ty** [comment]
What command are you running from that bat?
Could you [dump logs](https://github.com/sc0ty/subsync/wiki/How-to-dump-logs)?

**Comment by Tupilak** [comment]
Command is
subsync-cmd.exe sync --sub e:\Anna.2019.25fps.da.srt --ref "E:/Anna (2019).mp4" --sub-lang DAN --out E:\anna_new.srt

I'll make a dump when I have more time.

**Comment by Tupilak** [comment]
Log is at https://www.dropbox.com/s/i83m4fr7r26jtx7/subsync.rar?dl=0
I can see I don't get the error when I use the --loglevel=DEBUG parameter
Also command line is :
subsync-cmd.exe --loglevel=DEBUG --logfile=e:\subsync.log sync --sub "Anna (2019).da.srt" --ref "Anna (2019).mp4" --sub-lang DAN --out Anna_new.srt

**Comment by sc0ty** [comment]
So you are seeing this error message only when you run GUI without setting `--loglevel=DEBUG`? Do I understand correctly? That's very strange.
Could you check if you get this popup with `--loglevel=INFO` or `WARNING`? Just logs with this popup, no need for synchronization.

> MainThread: WARNING: subsync.translations: translation language setup failed, FileNotFoundError(2, 'No translation file found for domain')

This shows up only in console output right? That means it has no Danish translation for subsync interface, its unrelated.

> "Traceback (most recent call last):
File "subsync\gui\errorwin.py", line 75, in wrapper
File "subsync\gui\openwin.py", line 67, in openStream"

You are getting this when you run GUI and load file manually or from command line? And if from command line, is it the same command as you posted for subsync-cmd.exe?

I can see that you are setting `--sub-lang` with upper cases. It shouldn't matter, but internally all language codes are processed as lower cases, so could you also check with `dan` just to be sure?

Thanks for your help and sorry for this long list of requests, but as you can see, I don't know whats going on.

**Comment by Tupilak** [comment]
I think we need to get it right. The first error I get when I use subsync-cmd.exe in command promt. The error don't show up then I use the debug parameter

The second error I get when ever I try to load a video file in the GUI, at all time
I have not made a log file from the GUI, so here it is, with a screenshot of the error as well : https://www.dropbox.com/s/kqhjcij545z5mr3/Subsync%20error.rar?dl=0

**Comment by sc0ty** [comment]
Ok, I know whats going on.
You are opening `Anna (2019).mp4` as subtitle and you should open it as reference. Since there is no subtitles muxed in this file, subsync complains "There are no usable streams". Everything works as intended.

**Comment by Tupilak** [comment]
Ohh shit... I need to read better. Sorry

**Comment by sc0ty** [comment]
No worries
