### ISSUE TITLE
No command line output on Windows

### ISSUE THREAD

**Issue by risk00** [sc0ty/subsync#87]
Can someone please give me an example of how to sync titles from a command line? I am using subsync-0.15.0-portable-amd64.exe (portable version - without installation)

Thank you.

**Comment by sc0ty** [comment]
There is an issue with Windows builds not showing command line output. You could use version with installer - there is `subsync-cmd.exe` which doesn't have this problem.

**Comment by risk00** [comment]
Thank you for pointing that out. I'll use the installer version. Could you please write back a sync command line example?

**Comment by sc0ty** [comment]
Example:
```
subsync-cmd --cli sync --sub=subtitles.srt --sub-lang=pol --ref=video.avi --ref-lang=eng --out=output.srt
```
For details look [here](https://github.com/sc0ty/subsync/wiki/Command-line-options).

And I found possible workaround for this issue, will test it later: https://github.com/xlwings/xlwings/blob/master/xlwings/server.py#L111
