### ISSUE TITLE
Support `brew cask install subsync` 

### ISSUE THREAD

**Issue by zx8** [sc0ty/subsync#88]
It would be great if those of us using macOS were able to `brew cask install subsync`.

Thoughts?

**Comment by sc0ty** [comment]
Whats wrong with the current installer?

**Comment by zx8** [comment]
I wouldn't say there's anything wrong with the installer itself, it's more that `brew` is the de facto standard for macOS users for managing their CLI tools nowadays (`brew install`), as well as for GUI applications (`brew cask install`) – it's as common as `apt` is on Linux.

As an example, the first thing I tried when I found `subsync` was to `brew install subsync`, followed by `brew cask install subsync`, to no avail, of course. 😄 

`brew` also has other advantages:
- automatic upgrades when a new version of `subsync` is released
- automatic dependencies, e.g. I had to `brew install cmu-pocketsphinx cmu-sphinxbase` when compiling the `subsync` CLI tool because they're not present on macOS by default

I'd be happy to help out if you're on board with it!

**Comment by sc0ty** [comment]
Ok, assuming releasing each new version will not require much work, I'm all for it.
But I've never published anything with brew, so your help will be appreciated.

**Comment by zx8** [comment]
Ok, I've raised a PR to add `subsync` to `brew` 😄 

https://github.com/Homebrew/homebrew-cask/pull/84745

**Comment by vitorgalvao** [comment]
> assuming releasing each new version will not require much work

You don’t have to do it yourself, users can do it. But if you want to, it’s just a matter of [some simple setup](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask) and then `cask-repair --cask-version NEW_VERSION subsync`, which will do everything for you, including submitting the PR.

**Comment by sc0ty** [comment]
Ok, thanks guys.
@zx8 I can see that you put line `url "https://github.com/sc0ty/subsync/releases/download/0.15/subsync-#{version}-mac-x86_64.dmg"`. Shouldn't the 0.15 part be replaced with variable so it could be updated as @vitorgalvao posted?

`zap trash` will be called to cleanup when uninstall, right? If so, it should also contain `~/Library/Preferences/subsync/assets.json`. Or maybe entire `~/Library/Preferences/subsync`, we may have other files there in the future.

Also I'd like it to use dependencies from brew (ffmpeg or libav and pocketsphinx), but as I understand it would require separate release?

**Comment by zx8** [comment]
@sc0ty Aha, nice catch, have updated the `zap` 👉 https://github.com/Homebrew/homebrew-cask/pull/84745/commits/c2e7b677425e33398e937f2f04dee8bf7b33bc50

Also updated the `0.15` with a variable 👉 https://github.com/Homebrew/homebrew-cask/commit/acf259304541810df9b12d314f54dfce67cabfec

In terms of how `brew cask` interact with `brew`, I'm not entirely sure so I'll leave that to @vitorgalvao to clarify.

Let's continue the discussion @ https://github.com/Homebrew/homebrew-cask/pull/84745 for sake of ease.

**Comment by vitorgalvao** [comment]
> `zap trash` will be called to cleanup when uninstall, right?

It’s only called when doing `brew cask zap CASK_NAME`, which runs an `uninstall` first. But yes, those files you mentioned are a fit there.

> Also I'd like it to use dependencies from brew (ffmpeg or libav and pocketsphinx), but as I understand it would require separate release?

Homebrew and Homebrew Cask behave differently. If the app itself doesn’t work out of the box and requires some dependencies that are provided by Homebrew, add a [`depends_on formula:`](https://github.com/Homebrew/homebrew-cask/blob/be2e3c6f195016afa2987bc668563732cbb6f0ce/Casks/cellery.rb#L12).

**Comment by sc0ty** [comment]
Closing here since it's already merged to homebrew repo.
Thanks guys for your work.
