### ISSUE TITLE
Error synchronizing subs

### ISSUE THREAD

**Issue by ElimGarak72** [sc0ty/subsync#89]
Hello. I'm getting errors while trying to synchronize these 3 subtitles. I don't know what the problem may be.
I've checked and they are the right ones for the references and they don't seem to include any special character.
Thanks

[Season 4.zip](https://github.com/sc0ty/subsync/files/4824519/Season.4.zip)

**Comment by sc0ty** [comment]
Probably one of [these](https://github.com/sc0ty/subsync/wiki/FAQ#why-it-failed-to-synchronize-my-subtitles) cases (I've edited it just now because it was phrased somewhat confusing).

**Comment by ElimGarak72** [comment]
Hi sc0ty and first of all thank you for your answer.
I guess I've found the issue. As you can see, at the beginning of syncronizing there's a max change of 44+ minutes. 

![image](https://user-images.githubusercontent.com/67368032/85921425-33067600-b874-11ea-86c5-dabd49cdb4c4.png)

That's impossibile, since the reference is 28 minutes only.

![image](https://user-images.githubusercontent.com/67368032/85921445-58937f80-b874-11ea-8073-41f926e09ccc.png)

Also, the sub file timings are about just one minute off.

![image](https://user-images.githubusercontent.com/67368032/85921466-6ea14000-b874-11ea-884c-c92a4984a262.png)

Subsync doesn't create a log file for me, even though I've set it as "All".

![image](https://user-images.githubusercontent.com/67368032/85921488-8ed0ff00-b874-11ea-8780-c0f3b8e92bca.png)

But I hope the info I gave you can help you track the problem anyway.

Thanks again!

**Comment by ElimGarak72** [comment]
EDIT:
I've been able to create a log unchecking "Enable advanced debug options". Please find it attached.
[log.txt](https://github.com/sc0ty/subsync/files/4840448/log.txt)

**Comment by sc0ty** [comment]
Could you dump also words used by correlator? Just run subsync with following arguments and start synchronization
`subsync.exe --dump-words "subRaw:U:\Incoming\Serie TV\Sex and the City\Season 4\sub.srt"  --dump-words "refRaw:U:\Incoming\Serie TV\Sex and the City\Season 4\ref.srt"`
Thanks.

**Comment by ElimGarak72** [comment]
Hello. Thanks again for your help. Please find the sub.srt and ref.srt files attached.
[Season 4.zip](https://github.com/sc0ty/subsync/files/4845435/Season.4.zip)

**Comment by sc0ty** [comment]
Do you have proper subtitles for this episode? I've just downloaded it and it starts with different lines than what's in your screenshot.

**Comment by ElimGarak72** [comment]
Hi! You can find them attached to my first message. Thanks!

**Comment by sc0ty** [comment]
Yep, that's not subtitles for this episode.
Also if you look at 4x17 and 4x18 you posted - its the same file, so probably its the same problem.

**Comment by ElimGarak72** [comment]
Gosh, I feel so stupid now. I didn't consider the possibility.
I'm very sorry for wasting your time and very grateful.
Thanks!

**Comment by ElimGarak72** [comment]
Also, do you consider requests? ^__^
I'd really love for SubSync to have some "Cleaning" options to check/uncheck.

1) Strip text between parentheses ( )
2) Strip text between curly brackets { }
3) Strip text between angle brackets < >
4) Strip text between square brackets [ ]
5) Strip text between asterisks * ... *
6) Strip any cue containing a music note (♪)
7) Strip speaking character labels

Heave a great day!

**Comment by sc0ty** [comment]
Sorry, but I won't add any editing options.
The reason is prosaic: I prefer to spend my time on improving main function of SubSync which is synchronization. There is already plenty of subtitle editors available online. And maybe your request seems to be a small feature, they never are. E.g. if I want this to be useful for larger group of people, it would need some configuration options, where you could choose what to remove. This should be available both from GUI and command line arguments. And eventually it grows and I'm spending my time implementing it, testing and fixing bugs.
