### ISSUE TITLE
Missing Danish > There is no dictionary for transaltion from eng to dan

### ISSUE THREAD

**Issue by wazerstar** [sc0ty/subsync#9]
How can we get this implemented?

**Comment by sc0ty** [comment]
We need to find some Danish - English dictionary with permissive licence, so we could use its database. It must be converted to format described in https://github.com/sc0ty/subsync/blob/master/doc/assets.md#dictionary

Recently I found this project https://freedict.org/. Importing their dictionaries is on my to do list, and they have Danish - English dict.

**Comment by sc0ty** [comment]
done

**Comment by wazerstar** [comment]
@sc0ty Seems to be working good for a sample I just did, good job! Will let you know if anything comes up, again thumbs up!
