### ISSUE TITLE
Feature request: export points in csv or similar format

### ISSUE THREAD

**Issue by karlak** [sc0ty/subsync#91]
It would be a nice addition to be able to get the points in order to compute a graph showing at a glance if the resulting subtitles seem correct. 

Thanks!

**Comment by sc0ty** [comment]
There is such option already in debug options.
You have to `enable advanced debug options` in settings, debug tab. Then you will see new menu button in synchronization window with (among other) `Dump used synchronization points`.

**Comment by karlak** [comment]
Ah, I searched for it in the settings. Thanks you for your help ! I'll close this issue.
