### ISSUE TITLE
Rewrite/Replace Old Subtitle File

### ISSUE THREAD

**Issue by rmanzt** [sc0ty/subsync#92]
In batch mode, is there a way to have subsync rewrite the existing subtitle file so there aren't two copies afterwards (old one plus the new subsync generated one)?

I noticed an option is settings>confirm overwrite of file with popup -- but it doesn't seem to do anything.

After batch processing I was left with two subtitle files in my movies folder.

**Comment by sc0ty** [comment]
That option just dismiss confirmation popup when you are overwriting existing subtitles.
You need to set output path to be the same as input. To do that, select files in "output" column, click "Select output" button and set "output directory" and "file name": "same as input subtitles", clear "append language code" and "append stream number" and select file type same as input. And of course check "overwrite existing files".
![Screenshot_2020-07-15_21-38-49](https://user-images.githubusercontent.com/1812478/87588245-9bae7900-c6e3-11ea-9826-4304e1560ee5.png)

**Comment by aaron-typo** [comment]
I am trying to do the same thing here. When I use your settings I get an error message for each output file:

`Couldn't save synchronized subtitles
Can't save subtitle file. [Errno 13] Permission denied: 'Z:\\xyz\\Season 1\\xyz - S01E01 - Episode 1.en.srt'
encoding: UTF-8
path: Z:\xyz\Season 1\xyz - S01E01 - Episode 1.en.srt
`
When the output file name is not the same as the input subtitle file name it works without any errors.

**Comment by sc0ty** [comment]
To be honest I never tried to overwrite subtitles that way. When subsync is saving subtitles, input file is still opened for read. I've seen this working on Linux, but apparently not on Windows.

**Comment by aaron-typo** [comment]
Is there any chance this might get fixed in the future? If not, what would you suggest as a procedure if you wanted to sync the subs (multi languages) for a whole collection of tv-shows?

**Comment by sc0ty** [comment]
I think I already did that accidentally during refactoring. Will have to verify that yet.
And in the meantime you could point output to different directory and overwrite them all at once using file explorer after synchronization.

**Comment by sc0ty** [comment]
It should work now
