### ISSUE TITLE
Not an Issue - Synching without Timings?

### ISSUE THREAD

**Issue by rusemode** [sc0ty/subsync#95]
I'm probably wrong asking this in the issue page, but is there any way to synch an .srt without timings?
I have a transcription but all of the lines have the same exact timing (already tried running it, no luck, treats it as one line)
If I change the timings, (which are not 0 but rather -5min25secs to 6min33secs for example, this for every line), to 00.00.00, could subsynch eventually listen to the audio and time the blank lines?

If this feature is not available, could it be worked into the code, or is it far too complex for the system?

**Comment by sc0ty** [comment]
Sorry for this late reply, I've managed to miss this issue somehow.

Unfortunately subsync can't generate timecodes from nothing. It relies on existing timecodes during synchronization. For more information see [FAQ](https://github.com/sc0ty/subsync/wiki/FAQ#why-it-failed-to-synchronize-my-subtitles).

**Comment by theor** [comment]
Note: Aeneas https://github.com/readbeyond/aeneas does that, and well in my experience
