### ISSUE TITLE
Asset Dictionary missing (Bazarr 0.9.0.4)

### ISSUE THREAD

**Issue by RikP** [sc0ty/subsync#96]
There is an issue where post processing is broken in bazarr in version 0.9.0.3
This has been fixed in 0.9.0.4 (development build).

I tested this today and subsync is called but i am getting the following error:
```
[+] updating asset list [!] there is no assets needed to perform synchronization [-] asset dictionary None / Dutch is missing 
```

I think the None in that message is not correct. Is this something bazarr is wrongly sending to sybsync?

My command is:
```
subsync --cli sync --ref-lang '{{episode_language_code3}}'  --sub '{{subtitles}}' --ref '{{episode}}' --out '{{subtitles}}' --overwrite
```

**Comment by sc0ty** [comment]
Could you dump logs? https://github.com/sc0ty/subsync/wiki/How-to-dump-logs#from-command-line

I can't reproduce this myself. It looks like there is some problem with subtitle language detection, but it shouldn't try to use dictionary if subtitle language isn't set and can't be deduced.

**Comment by RikP** [comment]
So running the development version of bazarr now and it seems to work. I think it was an issue on the bazarr side. This can be closed
