### ISSUE TITLE
Synchronization gets stuck at 20 points and fails

### ISSUE THREAD

**Issue by Ocman76** [sc0ty/subsync#98]
Hi sc0ty,

I am having a recurring issue where trying to sync subtitles to audio reaches 20 points and fails.  It is occurring across a range of different media and I have been unable to figure out why.  Here is a log of it occurring for one .srt/.mkv file set, if there are any other logs/files I can provide that would help in troubleshooting please let me know.

[Subsync.log](https://github.com/sc0ty/subsync/files/5456826/Subsync.log)

Thank you for all your work on subsync!

**Comment by sc0ty** [comment]
Hi,
Probably your subtitles can't be synchronized with this algorithm, see [FAQ](https://github.com/sc0ty/subsync/wiki/FAQ#why-it-failed-to-synchronize-my-subtitles).
If that's not the case, you could try to decrease _min points no_ in settings to 10 and try again, but still it could fail or you could get false positive (it shows success but subtitles are not aligned correctly).

**Comment by Ocman76** [comment]
Thanks for the reply.  Usually when I have this issue I am able to get the video to synchronize correctly with another subtitle file but when I manually compare the two .srt files to see why one fails and the other doesn't they are usually almost identical.  I would expect the one that fails to be missing lines or have additional lines of dialogue that do not occur in the video.  Regardless if I am able to get other subtitles to work it isn't a real problem.

Cheers!

**Comment by avraham** [comment]
Hi,
Thank you for this tool. It's really great.

I had this issue too, and I understand that this can happen in some special occasions, but would it be possible to exit the process and return an error instead of just getting stuck?
I'm trying to use this script in an automated way and I want to be able to do something in these situations.

Thank you for your work.
