### ISSUE TITLE
Feature Request: Default folder

### ISSUE THREAD

**Issue by DocJellyBean** [sc0ty/subsync#99]
I love this app, and it has worked for me everytime 👍 

It would be great if one could specify a default folder where the files are located in Settings, because at the moment it remembers the last location as long as there is a file there. If it is empty, it reverts to the decault which seems to be Documents.

**Comment by sc0ty** [comment]
Now it remembers last used location. I Imagine most people have video and subtitles in one folder, and they saving to the same folder. That way you have to select directory only once.

You could drag and drop files directly to the window.
